local Logger = require("sebaestschjin-tts.Logger")
local StringUtil = require("sebaestschjin-tts.StringUtil")
local TableUtil = require("sebaestschjin-tts.TableUtil")

--- Contains information about different parts of the Gloomhaven mod and Gloomhaven components (e.g.
--- all classes and their perks).
local Game = {}

local FoundAbility = {
    None = 0,
    Exact = 1,
    Nearest = 2,
}

---@param className string
---@return gh_Game_Class
function Game.class(className)
    local classInfo = Game.Classes[className]
    if not classInfo then
        Logger.error("Tried to get class information for class '%s', but it doesn't exist!", className)
    end
    return classInfo
end

---@param className string
---@param perk number
---@return gh_Game_Perk, number
function Game.perk(className, perk)
    local allPerks = Game.class(className).perks
    local perkInfo = allPerks[perk]

    if perkInfo.mapTo ~= nil then
        local perkIndex = --[[---@not nil]] perkInfo.mapTo
        return allPerks[perkIndex], perkIndex
    end

    return perkInfo, perk
end

---@param className string
---@param perk number
---@return number
function Game.internalToRealPerk(className, perk)
    for perkIndex, perkInfo in ipairs(Game.class(className).perks) do
        if perkInfo.mapTo == perk then
            return perkIndex
        end
    end

    return perk
end

---@param className string
---@param abilityName string
---@return nil | gh_Game_Ability
function Game.ability(className, abilityName)
    local ability, state = Game.nearestAbility(className, abilityName)

    if state == FoundAbility.Nearest then
        Logger.warn("Tried to get ability information for '%s' of class '%s', but it doesn't exist."
                .. " However, found the ability '%s' which is similar in name which will be used instead."
                .. " Maybe there's a typo in the ability name."
                .. " Please verify that this assumption is correct.",
                abilityName, className, (--[[---@not nil]] ability).name)
    elseif state == FoundAbility.None then
        local classInfo = Game.class(className)
        local allNames = TableUtil.keys(classInfo.abilities)
        Logger.error("Tried to get ability information for '%s' of class '%s', but it doesn't exist!"
                .. " Also couldn't find any ability that is similar. Avaible abilities are: [%s].",
                abilityName, className, table.concat(allNames, ", "))
    end

    return ability
end

---@param className string
---@param abilityName string
---@return nil | gh_Game_Ability, number
function Game.nearestAbility(className, abilityName)
    local classInfo = Game.class(className)
    local state = FoundAbility.None
    if classInfo then
        local abilityInfo = classInfo.abilities[abilityName]
        if not abilityInfo then
            local allNames = TableUtil.keys(classInfo.abilities)
            local nearestName = StringUtil.findNearest(abilityName, allNames, 3)
            if nearestName then
                abilityInfo = classInfo.abilities[--[[---@not nil]]nearestName]
                abilityInfo.name = nearestName
                state = FoundAbility.Nearest
            end
        else
            abilityInfo.name = abilityName
            state = FoundAbility.Exact
        end

        return abilityInfo, state
    end
    return nil, state
end

---@param ability gh_Game_Ability
---@return boolean
function Game.isStartingAbility(ability)
    return ability.level == 1 or ability.level == "X"
end

---@param className string
---@return string[]
function Game.startingAbilities(className)
    local abilities = --[[---@type string[] ]] {}
    for abilityName, ability in pairs(Game.class(className).abilities) do
        if Game.isStartingAbility(ability) then
            table.insert(abilities, abilityName)
        end
    end
    return abilities
end

---@param quest gh_Save_Quest
---@return gh_Game_Quest_Info
function Game.quest(quest)
    local questByName = Game.Quests[--[[---@type string]] quest]
    if questByName then
        return {
            name = --[[---@type string]] quest,
            number = questByName.number,
            index = questByName.index,
        }
    end

    for questName, questInfo in pairs(Game.Quests) do
        if questInfo.number == quest then
            return {
                name = questName,
                number = questInfo.number,
                index = questInfo.index,
            }
        end
    end
end

---@type table<gh_Game_Difficulty, number>
Game.Difficulty = {
    Easy = -1,
    Normal = 0,
    Hard = 1,
    ["Very Hard"] = 2,
}

--- Max HP per level.
---@type table<string, gh_Game_HpProgression>
local HpProgression = {
    Low = { 6, 7, 8, 9, 10, 11, 12, 13, 14 },
    Medium = { 8, 9, 11, 12, 14, 15, 17, 18, 20 },
    High = { 10, 12, 14, 16, 18, 20, 22, 24, 26 }
}

--- XP Requirements per level
---@type number[]
Game.XpRequirements = { 0, 45, 95, 150, 210, 275, 345, 420, 500 }

Game.Items = {
    ---Max item number per prosperity level
    ---@type number[]
    Prosperity = { 14, 21, 28, 35, 42, 49, 56, 63, 70 },
    ---@type table<string, number>
    NegativeEffects = {
        ["Hide Armor"] = 2,
        ["Heavy Greaves"] = 1,
        ["Chain Mail"] = 3,
        ["Heavy Basinet"] = 2,
        ["Splintmail"] = 4,
        ["Steel Sabatons"] = 2,
        ["Platemail"] = 5,
        ["Swordedge Armor"] = 4,
        ["Chain Hood"] = 1,
    },
    -- In older versions of the mod, some items don't have a description, so it won't be identified as an item card.
    -- Thus, the items are listed here with their information.
    ---@type table<string, gh_Game_Items>
    List = {
        ["Boots of Striding"] = {
            prosperity = 1,
        },
        ["Empowering Talisman"] = {
            prosperity = 2,
        },
        ["Minor Mana Potion"] = {
            prosperity = 2,
        },
        ["Minor Stamina Potion"] = {
            prosperity = 1,
        },
        ["Minor Power Potion"] = {
            prosperity = 1,
        },
        ["Sacrificial Robes"] = {
            reward = "loot",
        },
        ["Volatile Bomb"] = {
            prosperity = 4,
        },
        ["Wand of Tremors"] = {
            reward = "random",
        },
    }
}

---@type table<number, number>
Game.RandomScenarios = {
    [63] = 0,
    [64] = 1,
    [65] = 2,
    [66] = 3,
    [67] = 4,
    [68] = 5,
    [69] = 6,
    [70] = 7,
    [71] = 8,
}

--- Information about all character classes.
---@type table<string, gh_Game_Class>
Game.Classes = {
    Brute = {
        isStartingClass = true,
        boxGuid = "697f18",
        playerMat = 2,
        hp = HpProgression.High,
        perks = {
            [1] = { remove = { "(-1)", "(-1)" } },
            [2] = { add = { "(+1)" }, remove = { "(-1)" } },
            [3] = { add = { "(+1)", "(+1)" } },
            [4] = { add = { "(+1)", "(+1)" } },
            [5] = { add = { "(+3)" } },
            [6] = { add = { "(Push 1) (Rolling)", "(Push 1) (Rolling)", "(Push 1) (Rolling)" } },
            [7] = { add = { "(Push 1) (Rolling)", "(Push 1) (Rolling)", "(Push 1) (Rolling)" } },
            [8] = { add = { "(Pierce 3) (Rolling)", "(Pierce 3) (Rolling)" } },
            [9] = { add = { "(Stun) (Rolling)" } },
            [10] = { add = { "(Stun) (Rolling)" }, mapTo = 13 },
            [11] = { add = { "(Disarm) (Rolling)", "(Muddle) (Rolling)" }, mapTo = 10 },
            [12] = { add = { "(Add Target) (Rolling)" }, mapTo = 11 },
            [13] = { add = { "(Add Target) (Rolling)" }, mapTo = 12 },
            [14] = { add = { "(+1) (Shield 1 Self)" } },
            [15] = { add = { "(+1)" }, ignore = "I" }
        },
        abilities = {
            ["Eye for an Eye"] = { level = 1,
                                   enhancements = { [1] = { -0.46, -0.96 }, [2] = { -0.35, 0.54 }, [3] = { -0.55, 0.54 } }
            },
            ["Trample"] = { level = 1,
                            enhancements = { [1] = { -0.41, -0.66 }, [2] = { -0.35, -0.47 }, [3] = { -0.41, 0.38 }, [4] = { -0.41, 0.76 }, [5] = { -0.61, 0.76 } }
            },
            ["Grab and Go"] = { level = 1,
                                enhancements = { [1] = { -0.41, 0.74 }, [2] = { -0.61, 0.74 } }
            },
            ["Overwhelming Assault"] = { level = 1,
                                         enhancements = { { -0.41, -0.72 }, { -0.61, -0.72 }, { -0.41, 0.8 } }
            },
            ["Provoking Roar"] = { level = 1,
                                   enhancements = { { -0.41, -0.66 } }
            },
            ["Shield Bash"] = { level = 1,
                                enhancements = { { -0.41, -0.79 }, { -0.61, -0.79 }, { -0.41, 0.55 }, { -0.61, 0.55 } }
            },
            ["Sweeping Blow"] = { level = 1,
                                  enhancements = { { -0.09, -0.58 }, { -0.23, -0.77 }, { -0.4, 0.8 } }
            },
            ["Warding Strength"] = { level = 1,
                                     enhancements = { { -0.41, -0.65 }, { -0.33, -0.47 } }
            },
            ["Leaping Cleave"] = { level = 1,
                                   enhancements = { { -0.41, -0.28 }, { -0.07, -0.69 }, { -0.41, 0.56 } }
            },
            ["Spare Dagger"] = { level = 1,
                                 enhancements = { { -0.41, -0.79 }, { -0.41, 0.74 } }
            },
            ["Wall of Doom"] = { level = "X",
                                 enhancements = { { -0.46, -0.97 }, { -0.41, -0.61 } }
            },
            ["Skewer"] = { level = "X",
                           enhancements = { { -0.05, -0.85 }, { -0.64, -1.02 }, { -0.41, 0.62 }, { -0.61, 0.62 } }
            },
            ["Balanced Measure"] = { level = "X",
                                     enhancements = {}
            },
            ["Fatal Advance"] = { level = 2,
                                  enhancements = { { -0.41, 0.77 } }
            },
            ["Juggernaut"] = { level = 2,
                               enhancements = { { -0.41, -0.71 }, { -0.41, -0.47 } }
            },
            ["Hook and Chain"] = { level = 3,
                                   enhancements = { { -0.41, -0.71 }, { -0.61, -0.71 } }
            },
            ["Brute Force"] = { level = 3,
                                enhancements = { { -0.05, -0.74 }, { -0.25, -0.77 }, { -0.25, -0.38 }, { -0.41, 0.66 } }
            },
            ["Unstoppable Charge"] = { level = 4,
                                       enhancements = { { -0.41, -0.72 }, { -0.41, 0.54 } }
            },
            ["Devastating Hack"] = { level = 4,
                                     enhancements = { { -0.41, -0.72 }, { -0.61, -0.72 } }
            },
            ["Whirlwind"] = { level = 5,
                              enhancements = { { -0.41, -0.73 }, { -0.41, 0.57 }, { -0.41, 0.82 } }
            },
            ["Skirmishing Maneuver"] = { level = 5,
                                         enhancements = { { -0.41, -0.58 }, { -0.41, 0.56 } }
            },
            ["Quietus"] = { level = 6,
                            enhancements = { { -0.41, 0.5 } }
            },
            ["Immovable Phalanx"] = { level = 6,
                                      enhancements = { { -0.41, -0.79 }, { -0.41, -0.57 } }
            },
            ["Defensive Tactics"] = { level = 7,
                                      enhancements = { { -0.41, -0.94 }, { -0.32, -0.65 } }
            },
            ["Crippling Offensive"] = { level = 7,
                                        enhancements = { { -0.41, -0.87 }, { -0.61, -0.87 }, { -0.41, 0.48 } }
            },
            ["Selfish Retribution"] = { level = 8,
                                        enhancements = { { -0.41, -0.72 }, { -0.41, 0.4 }, { -0.46, 0.66 } }
            },
            ["Frenzied Onslaught"] = { level = 8,
                                       enhancements = { { -0.41, -0.69 }, { -0.41, -0.24 } }
            },
            ["Face Your End"] = { level = 9,
                                  enhancements = { { -0.41, -0.95 }, { -0.33, -0.63 } }
            },
            ["King of the Hill"] = { level = 9,
                                     enhancements = { { -0.41, -0.81 }, { -0.61, -0.81 }, { -0.41, 0.72 } }
            },
        }
    },
    Scoundrel = {
        isStartingClass = true,
        boxGuid = "66309d",
        playerMat = 5,
        hp = HpProgression.Medium,
        perks = {
            [1] = { remove = { "(-1)", "(-1)" } },
            [2] = { remove = { "(-1)", "(-1)" } },
            [3] = { remove = { "(+0)", "(+0)", "(+0)", "(+0)" } },
            [4] = { remove = { "(-2)" }, add = { "(+0)" } },
            [5] = { remove = { "(-1)" }, add = { "(+1)" } },
            [6] = { remove = { "(+0)" }, add = { "(+2)" } },
            [7] = { remove = { "(+0)" }, add = { "(+2)" } },
            [8] = { add = { "(+1) (Rolling)", "(+1) (Rolling)" } },
            [9] = { add = { "(+1) (Rolling)", "(+1) (Rolling)" } },
            [10] = { add = { "(Pierce 3) (Rolling)", "(Pierce 3) (Rolling)" } },
            [11] = { add = { "(Poison) (Rolling)", "(Poison) (Rolling)" } },
            [12] = { add = { "(Poison) (Rolling)", "(Poison) (Rolling)" } },
            [13] = { add = { "(Muddle) (Rolling)", "(Muddle) (Rolling)" } },
            [14] = { add = { "(Invisible) (Rolling)" } },
            [15] = { ignore = "S" }
        },
        abilities = {
            ["Venom Shiv"] = { level = 1,
                               enhancements = { [1] = { -0.41, -0.77 }, [2] = { -0.41, 0.75 } }
            },
            ["Backstab"] = { level = 1,
                             enhancements = { [1] = { -0.41, -0.91 }, [2] = { -0.61, -0.91 } }
            },
            ["Throwing Knives"] = { level = 1,
                                    enhancements = { [1] = { -0.32, -0.69 } }
            },
            ["Quick Hands"] = { level = 1,
                                enhancements = { [1] = { -0.41, -0.7 }, [2] = { -0.41, -0.48 } }
            },
            ["Smoke Bomb"] = { level = 1,
                               enhancements = { [1] = { -0.5, -1 }, [2] = { -0.41, 0.67 }, [3] = { -0.33, 0.86 } }
            },
            ["Thief's Knack"] = { level = 1,
                                  enhancements = { [1] = { -0.41, 0.62 } }
            },
            ["Special Mixture"] = { level = 1,
                                    enhancements = { [1] = { -0.36, -0.64 }, [2] = { -0.41, 0.59 } }
            },
            ["Flanking Strike"] = { level = 1,
                                    enhancements = { [1] = { -0.41, -0.73 }, [2] = { -0.41, 0.75 } }
            },
            ["Swift Bow"] = { level = 1,
                              enhancements = { [1] = { -0.41, -0.66 }, [2] = { -0.32, -0.48 }, [3] = { -0.41, 0.61 } }
            },
            ["Sinister Opportunity"] = { level = "X",
                                         enhancements = { [1] = { -0.41, -0.84 }, [2] = { -0.41, 0.41 } }
            },
            ["Trickster's Reversal"] = { level = "X",
                                         enhancements = { [1] = { -0.41, -0.84 }, [2] = { -0.61, -0.84 } }
            },
            ["Single Out"] = { level = "X",
                               enhancements = { [1] = { -0.41, -0.74 } }
            },
            ["Open Wound"] = { level = 2,
                               enhancements = { [1] = { -0.41, -0.74 }, [2] = { -0.41, 0.74 } }
            },
            ["Flintlock"] = { level = 2,
                              enhancements = { [1] = { -0.41, 0.54 }, [2] = { -0.58, 0.54 }, [3] = { -0.34, 0.71 } }
            },
            ["Hidden Daggers"] = { level = 3,
                                   enhancements = { [1] = { -0.41, -0.87 }, [2] = { -0.33, -0.71 }, [3] = { -0.33, -0.54 }, [4] = { -0.5, 0.67 } }
            },
            ["Duelist's Advance"] = { level = 3,
                                      enhancements = { [1] = { -0.41, -0.71 }, [2] = { -0.41, -0.46 } }
            },
            ["Flurry of Blades"] = { level = 4,
                                     enhancements = { [1] = { -0.31, -0.72 }, [2] = { -0.41, 0.46 } }
            },
            ["Gruesome Advantage"] = { level = 4,
                                       enhancements = { [1] = { -0.41, -0.93 }, [2] = { -0.61, -0.93 } }
            },
            ["Visage of the Inevitable"] = { level = 5,
                                             enhancements = { [1] = { -0.41, 0.56 } }
            },
            ["Cull the Weak"] = { level = 5,
                                  enhancements = { [1] = { -0.41, -0.78 } }
            },
            ["Burning Oil"] = { level = 6,
                                enhancements = { [1] = { -0.41, -0.86 }, [2] = { -0.32, -0.68 } }
            },
            ["Crippling Poison"] = { level = 6,
                                     enhancements = { [1] = { -0.41, 0.49 } }
            },
            ["Stick to the Shadows"] = { level = 7,
                                         enhancements = { [1] = { -0.41, -0.74 }, [2] = { -0.61, -0.74 }, [3] = { -0.51, 0.77 } }
            },
            ["Spring the Trap"] = { level = 7,
                                    enhancements = {}
            },
            ["Stiletto Storm"] = { level = 8,
                                   enhancements = { [1] = { -0.33, -0.71 }, [2] = { -0.41, 0.47 }, [3] = { -0.46, 0.68 } }
            },
            ["Pain's End"] = { level = 8,
                               enhancements = { [1] = { -0.35, -0.79 }, [2] = { -0.54, -0.79 }, [3] = { -0.41, 0.61 } }
            },
            ["Watch It Burn"] = { level = 9,
                                  enhancements = { [1] = { -0.37, 0.57 }, [2] = { -0.46, 0.8 } }
            },
            ["Long Con"] = { level = 9,
                             enhancements = { [1] = { -0.41, -0.72 } }
            }
        }
    },
    Spellweaver = {
        isStartingClass = true,
        boxGuid = "0507cf",
        playerMat = 6,
        hp = HpProgression.Low,
        perks = {
            [1] = { remove = { "(+0)", "(+0)", "(+0)", "(+0)" } },
            [2] = { remove = { "(-1)" }, add = { "(+1)" } },
            [3] = { remove = { "(-1)" }, add = { "(+1)" } },
            [4] = { add = { "(+1)", "(+1)" } },
            [5] = { add = { "(+1)", "(+1)" } },
            [6] = { add = { "(+0) (Stun)" } },
            [7] = { add = { "(+1) (Wound)" } },
            [8] = { add = { "(+1) (Immobilize)" } },
            [9] = { add = { "(+1) (Curse)" } },
            [10] = { add = { "(+2) (Fire)" } },
            [11] = { add = { "(+2) (Fire)" } },
            [12] = { add = { "(+2) (Ice)" } },
            [13] = { add = { "(+2) (Ice)" } },
            [14] = { add = { "(Earth) (Rolling)", "(Air) (Rolling)" } },
            [15] = { add = { "(Dark) (Rolling)", "(Light) (Rolling)" } },
        },
        abilities = {
            ["Flame Strike"] = { level = 1,
                                 enhancements = { [1] = { -0.32, -0.61 }, [2] = { -0.41, 0.65 }, [3] = { -0.31, 0.81 } }
            },
            ["Freezing Nova"] = { level = 1,
                                  enhancements = { [1] = { -0.41, -0.85 }, [2] = { -0.35, 0.56 }, [3] = { -0.54, 0.56 } }
            },
            ["Fire Orbs"] = { level = 1,
                              enhancements = { [1] = { -0.41, -0.96 }, [2] = { -0.3, -0.78 }, [3] = { -0.3, -0.64 }, [4] = { -0.41, 0.74 } }
            },
            ["Frost Armor"] = { level = 1,
                                enhancements = { [1] = { -0.41, -0.77 } }
            },
            ["Mana Bolt"] = { level = 1,
                              enhancements = { [2] = { -0.37, 0.7 }, [3] = { -0.32, 0.88 }, [1] = { -0.41, -0.76 } }
            },
            ["Impaling Eruption"] = { level = 1,
                                      enhancements = { [1] = { -0.41, -0.98 }, [2] = { -0.32, -0.81 }, [3] = { -0.41, 0.74 } }
            },
            ["Ride the Wind"] = { level = 1,
                                  enhancements = { [1] = { -0.41, 0.56 } }
            },
            ["Reviving Ether"] = { level = 1,
                                   enhancements = { [1] = { -0.41, 0.62 } }
            },
            ["Hardened Spikes"] = { level = "X",
                                    enhancements = { [1] = { -0.46, -0.9 }, [2] = { -0.41, 0.58 } }
            },
            ["Crackling Air"] = { level = "X",
                                  enhancements = { [1] = { -0.41, 0.58 } }
            },
            ["Aid from the Ether"] = { level = "X",
                                       enhancements = { [1] = { -0.36, -0.67 }, [2] = { -0.33, -0.5 }, [3] = { 0.22, 0.64 }, [4] = { -0.24, 0.65 }, [5] = { -0.25, 0.84 } }
            },
            ["Icy Blast"] = { level = 2,
                              enhancements = { [1] = { -0.05, -0.87 }, [2] = { -0.37, 0.69 }, [3] = { -0.32, 0.87 } }
            },
            ["Flashing Burst"] = { level = 2,
                                   enhancements = { [1] = { -0.41, -0.78 }, [2] = { -0.31, -0.62 }, [3] = { -0.41, 0.72 } }
            },
            ["Elemental Aid"] = { level = 3,
                                  enhancements = { [1] = { -0.35, -0.76 }, [2] = { -0.31, -0.59 } }
            },
            ["Cold Fire"] = { level = 3,
                              enhancements = { [1] = { -0.32, -0.68 } }
            },
            ["Spirit of Doom"] = { level = 4,
                                   enhancements = {}
            },
            ["Forked Beam"] = { level = 4,
                                enhancements = { [1] = { -0.41, -0.85 }, [2] = { -0.33, -0.56 }, [3] = { -0.41, 0.73 } }
            },
            ["Engulfed in Flames"] = { level = 5,
                                       enhancements = { [1] = { -0.41, -0.79 }, [2] = { -0.3, -0.61 } }
            },
            ["Chromatic Explosion"] = { level = 5,
                                        enhancements = { [1] = { -0.11, -0.98 }, [2] = { -0.41, 0.64 } }
            },
            ["Frozen Night"] = { level = 6,
                                 enhancements = { [1] = { 0.01, -0.87 }, [2] = { -0.67, -0.79 }, [3] = { -0.76, -0.59 }, [4] = { -0.41, 0.56 } }
            },
            ["Living Torch"] = { level = 6,
                                 enhancements = { [1] = { -0.41, -0.87 }, [2] = { 0.2, 0.66 }, [3] = { -0.23, 0.65 }, [4] = { -0.23, 0.85 } }
            },
            ["Twin Restoration"] = { level = 7,
                                     enhancements = { [1] = { -0.41, 0.61 }, [2] = { -0.32, 0.93 } }
            },
            ["Stone Fists"] = { level = 7,
                                enhancements = { [1] = { -0.32, -0.79 }, [2] = { -0.41, 0.37 }, [3] = { -0.41, 0.58 } }
            },
            ["Cold Front"] = { level = 8,
                               enhancements = { [1] = { -0.07, -0.77 }, [2] = { 0.04, -0.62 } }
            },
            ["Zephyr Wings"] = { level = 8,
                                 enhancements = { [1] = { -0.41, 0.43 }, [2] = { -0.58, 0.43 } }
            },
            ["Inferno"] = { level = 9,
                            enhancements = { [1] = { -0.46, 0.48 } }
            },
            ["Black Hole"] = { level = 9,
                               enhancements = { [1] = { -0.41, 0.66 } }
            }
        }
    },
    Mindthief = {
        isStartingClass = true,
        boxGuid = "8c1ca4",
        playerMat = 4,
        hp = HpProgression.Low,
        perks = {
            [1] = { remove = { "(-1)", "(-1)" } },
            [2] = { remove = { "(-1)", "(-1)" } },
            [3] = { remove = { "(+0)", "(+0)", "(+0)", "(+0)" } },
            [4] = { remove = { "(+1)", "(+1)" }, add = { "(+2)", "(+2)" } },
            [5] = { remove = { "(-2)" }, add = { "(+0)" } },
            [6] = { add = { "(+2) (Ice)" } },
            [7] = { add = { "(+2) (Ice)" } },
            [8] = { add = { "(+1) (Rolling)", "(+1) (Rolling)" } },
            [9] = { add = { "(+1) (Rolling)", "(+1) (Rolling)" } },
            [10] = { add = { "(Pull 1) (Rolling)", "(Pull 1) (Rolling)", "(Pull 1) (Rolling)" } },
            [11] = { add = { "(Muddle) (Rolling)", "(Muddle) (Rolling)", "(Muddle) (Rolling)" } },
            [12] = { add = { "(Immobilize) (Rolling)", "(Immobilize) (Rolling)" } },
            [13] = { add = { "(Stun) (Rolling)" } },
            [14] = { add = { "(Disarm) (Rolling)", "(Muddle) (Rolling)" } },
            [15] = { ignore = "S" }
        },
        abilities = {
            ["Gnawing Horde"] = { level = 1,
                                  enhancements = { [1] = { 0.20, -0.72 }, [2] = { -0.24, -0.72 }, [3] = { 0.18, -0.52 }, [4] = { -0.41, 0.77 } }
            },
            ["Empathetic Assault"] = { level = 1,
                                       enhancements = { [1] = { -0.41, -0.86 }, [2] = { -0.61, -0.86 }, [3] = { -0.41, 0.55 }, [4] = { -0.37, 0.8 } }
            },
            ["Perverse Edge"] = { level = 1,
                                  enhancements = { [1] = { -0.41, -0.73 }, [2] = { -0.41, 0.49 }, [3] = { -0.33, 0.67 } }
            },
            ["Fearsome Blade"] = { level = 1,
                                   enhancements = { [1] = { -0.41, -0.77 }, [2] = { -0.33, -0.61 }, [3] = { -0.41, 0.74 }, [4] = { -0.61, 0.74 } }
            },
            ["Feedback Loop"] = { level = 1,
                                  enhancements = { [1] = { -0.41, -0.52 }, [2] = { -0.41, 0.38 } }
            },
            ["The Mind's Weakness"] = { level = 1,
                                        enhancements = { [1] = { -0.41, -0.53 }, [2] = { -0.41, 0.69 } }
            },
            ["Into the Night"] = { level = 1,
                                   enhancements = {}
            },
            ["Parasitic Influence"] = { level = 1,
                                        enhancements = { [1] = { -0.41, -0.5 } }
            },
            ["Scurry"] = { level = 1,
                           enhancements = { [1] = { -0.41, -0.72 }, [2] = { -0.41, -0.46 } }
            },
            ["Submissive Affliction"] = { level = 1,
                                          enhancements = { [1] = { -0.41, -0.86 } }
            },
            ["Frigid Apparition"] = { level = "X",
                                      enhancements = { [1] = { -0.41, -0.68 }, [2] = { -0.41, 0.42 } }
            },
            ["Possession"] = { level = "X",
                               enhancements = {}
            },
            ["Withering Claw"] = { level = "X",
                                   enhancements = { [1] = { -0.41, -0.53 } }
            },
            ["Wretched Creature"] = { level = 2,
                                      enhancements = { [1] = { 0.18, -0.74 }, [2] = { -0.24, -0.73 }, [3] = { 0.19, -0.52 }, [4] = { -0.41, 0.58 } }
            },
            ["Hostile Takeover"] = { level = 2,
                                     enhancements = { [1] = { -0.41, -0.87 }, [2] = { -0.32, -0.7 } }
            },
            ["Silent Scream"] = { level = 3,
                                  enhancements = { [1] = { -0.41, -0.51 }, [2] = { -0.41, 0.46 }, [3] = { -0.41, 0.71 } }
            },
            ["Brain Leech"] = { level = 3,
                                enhancements = { [1] = { -0.41, -0.97 }, [2] = { -0.37, -0.56 }, [3] = { -0.41, 0.56 } }
            },
            ["Cranium Overload"] = { level = 4,
                                     enhancements = { [1] = { -0.41, -0.72 }, [2] = { -0.61, -0.72 }, [3] = { -0.41, 0.76 } }
            },
            ["Pilfer"] = { level = 4,
                           enhancements = { [1] = { -0.41, 0.41 }, [2] = { -0.41, 0.63 }, [3] = { -0.41, 0.88 } }
            },
            ["Frozen Mind"] = { level = 5,
                                enhancements = { [1] = { -0.41, -0.51 } }
            },
            ["Mass Hysteria"] = { level = 5,
                                  enhancements = { [1] = { -0.34, -0.61 } }
            },
            ["Dark Frenzy"] = { level = 6,
                                enhancements = { [1] = { -0.41, -0.81 }, [2] = { -0.41, 0.42 }, [3] = { -0.41, 0.66 } }
            },
            ["Corrupting Embrace"] = { level = 6,
                                       enhancements = { [1] = { -0.41, -0.84 }, [2] = { -0.41, -0.46 }, [3] = { -0.41, 0.36 } }
            },
            ["Psychic Projection"] = { level = 7,
                                       enhancements = { [1] = { -0.35, -0.97 }, [2] = { -0.41, -0.65 } }
            },
            ["Vicious Blood"] = { level = 7,
                                  enhancements = { [1] = { -0.41, -0.51 }, [2] = { -0.41, 0.64 }, [3] = { -0.41, 0.88 } }
            },
            ["Domination"] = { level = 8,
                               enhancements = {}
            },
            ["Shared Nightmare"] = { level = 8,
                                     enhancements = { [1] = { -0.41, -0.99 }, [2] = { -0.34, -0.7 }, [3] = { -0.41, 0.62 } }
            },
            ["Many as One"] = { level = 9,
                                enhancements = { [1] = { 0.2, -0.72 }, [2] = { -0.24, -0.73 } }
            },
            ["Phantasmal Killer"] = { level = 9,
                                      enhancements = { [1] = { -0.41, -0.5 }, [2] = { -0.41, 0.35 } }
            }
        }
    },
    Cragheart = {
        isStartingClass = true,
        boxGuid = "ec1d2a",
        playerMat = 3,
        hp = HpProgression.High,
        perks = {
            [1] = { remove = { "(+0)", "(+0)", "(+0)", "(+0)" } },
            [2] = { remove = { "(-1)" }, add = { "(+1)" } },
            [3] = { remove = { "(-1)" }, add = { "(+1)" } },
            [4] = { remove = { "(-1)" }, add = { "(+1)" } },
            [5] = { add = { "(-2)", "(+2)", "(+2)" } },
            [6] = { add = { "(+1) (Immobilize)" } },
            [7] = { add = { "(+1) (Immobilize)" } },
            [8] = { add = { "(+2) (Muddle)" } },
            [9] = { add = { "(+2) (Muddle)" } },
            [10] = { add = { "(Push 2) (Rolling)", "(Push 2) (Rolling)" } },
            [11] = { add = { "(Earth) (Rolling)", "(Earth) (Rolling)" } },
            [12] = { add = { "(Earth) (Rolling)", "(Earth) (Rolling)" } },
            [13] = { add = { "(Air) (Rolling)", "(Air) (Rolling)" } },
            [14] = { ignore = "S" },
            [15] = { ignore = "I" }
        },
        abilities = {
            ["Avalanche"] = { level = 1,
                              enhancements = { [1] = { -0.01, -0.83 }, [2] = { -0.28, -0.79 } }
            },
            ["Rumbling Advance"] = { level = 1,
                                     enhancements = { [1] = { -0.36, -0.8 }, [2] = { -0.32, -0.63 }, [3] = { -0.41, 0.46 } }
            },
            ["Crater"] = { level = 1,
                           enhancements = { [1] = { -0.41, -0.79 }, [2] = { -0.32, -0.62 }, [3] = { -0.41, 0.63 } }
            },
            ["Unstable Upheaval"] = { level = 1,
                                      enhancements = { [1] = { -0.41, -1.01 } }
            },
            ["Backup Ammunition"] = { level = 1,
                                      enhancements = { [1] = { -0.41, 0.74 } }
            },
            ["Dirt Tornado"] = { level = 1,
                                 enhancements = { [1] = { -0.06, -0.9 }, [2] = { -0.41, 0.74 } }
            },
            ["Earthen Clod"] = { level = 1,
                                 enhancements = { [1] = { -0.41, -0.75 }, [2] = { -0.41, 0.69 }, [3] = { -0.33, 0.88 } }
            },
            ["Rock Tunnel"] = { level = 1,
                                enhancements = { [1] = { -0.41, 0.36 } }
            },
            ["Opposing Strike"] = { level = 1,
                                    enhancements = { [1] = { 0, -0.67 }, [2] = { -0.18, -0.67 } }
            },
            ["Massive Boulder"] = { level = 1,
                                    enhancements = { [1] = { -0.41, -0.93 }, [2] = { -0.32, -0.75 }, [3] = { -0.41, 0.75 } }
            },
            ["Crushing Grasp"] = { level = 1,
                                   enhancements = { [1] = { -0.41, -0.76 } }
            },
            ["Forceful Storm"] = { level = "X",
                                   enhancements = { [1] = { -0.16, -0.93 }, [2] = { -0.41, -0.8 } }
            },
            ["Heaving Swing"] = { level = "X",
                                  enhancements = { [1] = { -0.41, -0.96 }, [2] = { -0.31, -0.79 } }
            },
            ["Nature's Lift"] = { level = "X",
                                  enhancements = { [1] = { -0.35, -0.75 }, [2] = { -0.32, -0.58 }, [3] = { -0.33, -0.42 } }
            },
            ["Explosive Punch"] = { level = 2,
                                    enhancements = { [1] = { -0.41, -0.73 }, [2] = { -0.41, 0.74 } }
            },
            ["Sentient Growth"] = { level = 2,
                                    enhancements = { [1] = { -0.12, -0.92 }, [2] = { -0.07, -0.52 }, [3] = { -0.33, -0.68 }, [4] = { -0.36, 0.62 }, [5] = { -0.41, 0.99 } }
            },
            ["Blunt Force"] = { level = 3,
                                enhancements = { [1] = { -0.41, -0.86 }, [2] = { -0.61, -0.86 }, [3] = { -0.41, 0.43 }, [4] = { -0.46, 0.71 } }
            },
            ["Clear the Way"] = { level = 3,
                                  enhancements = { [1] = { -0.41, -0.64 }, [2] = { -0.41, 0.39 }, [3] = { -0.57, 0.39 } }
            },
            ["Kinetic Assault"] = { level = 4,
                                    enhancements = { [1] = { -0.37, -0.68 }, [2] = { -0.41, -0.44 }, [3] = { -0.46, 0.54 }, [4] = { -0.32, 0.71 } }
            },
            ["Rock Slide"] = { level = 4,
                               enhancements = {}
            },
            ["Petrify"] = { level = 5,
                            enhancements = { [1] = { -0.41, 0.55 } }
            },
            ["Stone Pummel"] = { level = 5,
                                 enhancements = { [1] = { -0.01, -0.78 }, [2] = { -0.06, -0.36 }, [3] = { -0.7, -0.75 } }
            },
            ["Dig Pit"] = { level = 6,
                            enhancements = { [1] = { -0.41, 0.55 } }
            },
            ["Cataclysm"] = { level = 6,
                              enhancements = { [1] = { -0.06, -0.87 }, [2] = { -0.41, 0.65 } }
            },
            ["Meteor"] = { level = 7,
                           enhancements = { [1] = { -0.41, -0.67 }, [2] = { -0.41, 0.68 } }
            },
            ["Brutal Momentum"] = { level = 7,
                                    enhancements = { [1] = { -0.41, -0.9 }, [2] = { -0.32, -0.72 } }
            },
            ["Lumbering Bash"] = { level = 8,
                                   enhancements = { [1] = { -0.41, -0.8 }, [2] = { -0.41, -0.59 } }
            },
            ["Rocky End"] = { level = 8,
                              enhancements = {}
            },
            ["Blind Destruction"] = { level = 9,
                                      enhancements = { [1] = { -0.31, -0.69 }, [2] = { -0.41, 0.42 } }
            },
            ["Pulverize"] = { level = 9,
                              enhancements = { [1] = { -0.41, -0.99 }, [2] = { -0.32, -0.82 }, [3] = { -0.41, 0.37 }, [4] = { -0.41, 0.98 } }
            }
        }
    },
    Tinkerer = {
        isStartingClass = true,
        boxGuid = "fdef02",
        playerMat = 7,
        hp = HpProgression.Medium,
        perks = {
            [1] = { remove = { "(-1)", "(-1)" } },
            [2] = { remove = { "(-1)", "(-1)" } },
            [3] = { remove = { "(-2)" }, add = { "(+0)" } },
            [4] = { add = { "(+1)", "(+1)" } },
            [5] = { add = { "(+3)" } },
            [6] = { add = { "(Fire) (Rolling)", "(Fire) (Rolling)" } },
            [7] = { add = { "(Muddle) (Rolling)", "(Muddle) (Rolling)", "(Muddle) (Rolling)" } },
            [8] = { add = { "(+1) (Wound)" } },
            [9] = { add = { "(+1) (Wound)" } },
            [10] = { add = { "(+1) (Immobilize)" } },
            [11] = { add = { "(+1) (Immobilize)" } },
            [12] = { add = { "(+1) (Heal 2 Self)" } },
            [13] = { add = { "(+1) (Heal 2 Self)" } },
            [14] = { add = { "(+0) (Add Target)" } },
            [15] = { ignore = "S" }
        },
        abilities = {
            ["Ink Bomb"] = { level = 1,
                             enhancements = { [1] = { -0.16, -0.91 }, [2] = { -0.41, 0.73 } }
            },
            ["Net Shooter"] = { level = 1,
                                enhancements = { [1] = { -0.25, -0.68 }, [2] = { -0.58, 0.55 }, [3] = { -0.41, 0.96 } }
            },
            ["Reinvigorating Elixir"] = { level = 1,
                                          enhancements = { [1] = { -0.34, -0.65 }, [2] = { -0.3, -0.49 } }
            },
            ["Flamethrower"] = { level = 1,
                                 enhancements = { [1] = { -0.05, -0.77 }, [2] = { -0.49, -0.84 }, [3] = { -0.7, -0.49 }, [4] = { -0.41, 0.55 } }
            },
            ["Harmless Contraption"] = { level = 1,
                                         enhancements = { [1] = { 0.2, -0.72 }, [2] = { -0.24, -0.73 }, [3] = { -0.35, 0.67 }, [4] = { -0.32, 0.83 } }
            },
            ["Energizing Tonic"] = { level = 1,
                                     enhancements = { [1] = { -0.35, -0.79 }, [2] = { -0.52, -0.79 }, [3] = { -0.41, 0.63 } }
            },
            ["Restorative Mist"] = { level = 1,
                                     enhancements = { [1] = { -0.36, -0.66 }, [2] = { -0.31, -0.5 }, [3] = { -0.41, 0.57 } }
            },
            ["Toxic Bolt"] = { level = 1,
                               enhancements = { [1] = { -0.3, -0.71 }, [2] = { -0.41, 0.57 }, [3] = { -0.3, 0.75 } }
            },
            ["Hook Gun"] = { level = 1,
                             enhancements = { [1] = { -0.31, -0.57 }, [2] = { -0.31, -0.39 } }
            },
            ["Proximity Mine"] = { level = 1,
                                   enhancements = { [1] = { -0.41, 0.75 } }
            },
            ["Enhancement Field"] = { level = 1,
                                      enhancements = { [1] = { -0.41, -0.64 } }
            },
            ["Stun Shot"] = { level = 1,
                              enhancements = { [1] = { -0.41, -0.73 }, [2] = { -0.31, -0.57 }, [3] = { -0.41, 0.73 } }
            },
            ["Volatile Concoction"] = { level = "X",
                                        enhancements = {}
            },
            ["Potent Potables"] = { level = "X",
                                    enhancements = { [1] = { -0.41, 0.74 } }
            },
            ["Reviving Shock"] = { level = "X",
                                   enhancements = { [1] = { -0.41, -0.74 }, [2] = { -0.31, -0.45 }, [3] = { -0.35, 0.56 }, [4] = { -0.52, 0.56 } }
            },
            ["Disorienting Flash"] = { level = 2,
                                       enhancements = { [1] = { -0.31, -0.69 }, [2] = { -0.31, -0.54 }, [3] = { -0.41, 0.95 } }
            },
            ["Stamina Booster"] = { level = 2,
                                    enhancements = { [1] = { -0.35, -0.66 } }
            },
            ["Tinkerer's Tools"] = { level = 3,
                                     enhancements = {}
            },
            ["Crank Bow"] = { level = 3,
                              enhancements = { [1] = { -0.41, -0.78 }, [2] = { -0.61, -0.78 }, [3] = { -0.41, 0.73 } }
            },
            ["Dangerous Contraption"] = { level = 4,
                                          enhancements = { [1] = { 0.2, -0.72 }, [2] = { -0.25, -0.73 }, [3] = { 0.2, -0.52 }, [4] = { -0.41, 0.73 } }
            },
            ["Micro Bots"] = { level = 4,
                               enhancements = { [1] = { -0.36, -0.78 }, [2] = { -0.55, -0.78 }, [3] = { -0.41, 0.64 } }
            },
            ["Noxious Vials"] = { level = 5,
                                  enhancements = { [1] = { -0.15, 0.49 }, [2] = { -0.23, 0.65 } }
            },
            ["Disintegration Beam"] = { level = 5,
                                        enhancements = { [1] = { -0.75, -1.01 }, [2] = { -0.41, 0.57 }, [3] = { -0.46, 0.81 } }
            },
            ["Gas Canister"] = { level = 6,
                                 enhancements = {}
            },
            ["Auto Turret"] = { level = 6,
                                enhancements = { [1] = { -0.36, 0.67 }, [2] = { -0.33, 0.85 } }
            },
            ["Curative Aerosol"] = { level = 7,
                                     enhancements = { [1] = { -0.35, -0.84 }, [2] = { -0.34, -0.32 }, [3] = { -0.35, 0.5 }, [4] = { -0.32, 0.8 } }
            },
            ["Murderous Contraption"] = { level = 7,
                                          enhancements = { [1] = { 0.2, -0.73 }, [2] = { -0.24, -0.72 }, [3] = { 0.19, -0.53 }, [4] = { -0.41, 0.67 }, [5] = { -0.3, 0.84 } }
            },
            ["Jet Propulsion"] = { level = 8,
                                   enhancements = { [1] = { -0.41, 0.56 } }
            },
            ["Harsh Stimulants"] = { level = 8,
                                     enhancements = { [1] = { -0.41, -0.8 }, [2] = { -0.58, -0.8 } }
            },
            ["Lethal Injection"] = { level = 9,
                                     enhancements = { { -0.41, 0.57 } }
            },
            ["Chimeric Formula"] = { level = 9,
                                     enhancements = {}
            }
        }
    },
    Berserker = {
        boxGuid = "7ff6c4",
        hp = HpProgression.High,
        perks = {
            [1] = { remove = { "(-1)", "(-1)" } },
            [2] = { remove = { "(+0)", "(+0)", "(+0)", "(+0)" } },
            [3] = { remove = { "(-1)" }, add = { "(+1)" } },
            [4] = { remove = { "(-1)" }, add = { "(+1)" } },
            [5] = { remove = { "(+0)" }, add = { "(+2) (Rolling)" } },
            [6] = { remove = { "(+0)" }, add = { "(+2) (Rolling)" } },
            [7] = { add = { "(Wound) (Rolling)", "(Wound) (Rolling)" } },
            [8] = { add = { "(Wound) (Rolling)", "(Wound) (Rolling)" } },
            [9] = { add = { "(Stun) (Rolling)" } },
            [10] = { add = { "(Stun) (Rolling)" } },
            [11] = { add = { "(+1) (Disarm) (Rolling)" } },
            [12] = { add = { "(Heal 1 Self) (Rolling)", "(Heal 1 Self) (Rolling)" } },
            [13] = { add = { "(+2) (Fire)" } },
            [14] = { add = { "(+2) (Fire)" } },
            [15] = { ignore = "I" }
        },
        abilities = {
            ["Dazing Wound"] = { level = 1,
                                 enhancements = { [1] = { -0.41, -0.78 }, [2] = { -0.41, 0.76 } }
            },
            ["Growing Rage"] = { level = 1,
                                 enhancements = { [1] = { -0.41, -0.86 }, [2] = { -0.41, 0.37 } }
            },
            ["Bounce Back"] = { level = 1,
                                enhancements = { [1] = { -0.48, -0.81 }, [2] = { -0.37, 0.79 } }
            },
            ["Cauterize"] = { level = 1,
                              enhancements = { [1] = { -0.41, -0.95 }, [2] = { -0.34, -0.66 } }
            },
            ["Resolute Stand"] = { level = 1,
                                   enhancements = { [1] = { -0.41, -0.86 }, [2] = { -0.41, 0.45 }, [3] = { -0.46, 0.68 } }
            },
            ["From the Brink"] = { level = 1,
                                   enhancements = { [1] = { -0.41, 0.58 }, [2] = { -0.41, 0.79 } }
            },
            ["Strength in Agony"] = { level = 1,
                                      enhancements = { [1] = { -0.41, -0.75 }, [2] = { -0.46, 0.71 } }
            },
            ["Defiance of Death"] = { level = 1,
                                      enhancements = { [1] = { -0.41, -0.79 }, [2] = { -0.61, -0.78 } }
            },
            ["Furious Aid"] = { level = 1,
                                enhancements = { [1] = { -0.41, 0.68 } }
            },
            ["Blood Pact"] = { level = 1,
                               enhancements = { [1] = { -0.41, -0.88 } }
            },
            ["Glass Hammer"] = { level = "X",
                                 enhancements = { [1] = { -0.46, -0.93 }, [2] = { -0.41, 0.71 } }
            },
            ["Unbridled Power"] = { level = "X",
                                    enhancements = { [1] = { -0.41, -0.77 } }
            },
            ["Numb the Pain"] = { level = "X",
                                  enhancements = { [1] = { -0.41, -0.88 }, [2] = { -0.41, 0.57 } }
            },
            ["Reckless Offensive"] = { level = 2,
                                       enhancements = { [1] = { -0.46, -0.72 }, [2] = { -0.61, -0.71 } }
            },
            ["Break the Chains"] = { level = 2,
                                     enhancements = { [1] = { -0.46, -0.8 }, [2] = { -0.36, -0.51 }, [3] = { -0.41, 0.45 } }
            },
            ["Fatal Fury"] = { level = 3,
                               enhancements = { [1] = { -0.41, 0.77 } }
            },
            ["Spiked Armor"] = { level = 3,
                                 enhancements = { [1] = { -0.41, 0.56 }, [2] = { -0.41, 0.79 } }
            },
            ["Flurry of Axes"] = { level = 4,
                                   enhancements = { [1] = { -0.41, -0.78 }, [2] = { -0.41, 0.74 } }
            },
            ["Shiny Distraction"] = { level = 4,
                                      enhancements = { [1] = { -0.41, -0.68 } }
            },
            ["Seeing Red"] = { level = 5,
                               enhancements = { [1] = { -0.41, -0.94 }, [2] = { -0.61, -0.93 } }
            },
            ["Final Fight"] = { level = 5,
                                enhancements = { [1] = { -0.41, 0.5 } }
            },
            ["Unstoppable Destruction"] = { level = 6,
                                            enhancements = { [1] = { -0.41, -0.76 } }
            },
            ["Devil Horns"] = { level = 6,
                                enhancements = { [1] = { -0.06, -0.76 }, [2] = { -0.29, -0.79 }, [2] = { -0.46, 0.61 } }
            },
            ["Burning Hatred"] = { level = 7,
                                   enhancements = { [1] = { -0.41, -0.83 }, [2] = { -0.41, 0.55 } }
            },
            ["Careless Charge"] = { level = 7,
                                    enhancements = { [1] = { -0.41, -0.9 }, [2] = { -0.46, -0.67 } }
            },
            ["Vengeful Barrage"] = { level = 8,
                                     enhancements = { [1] = { -0.41, 0.47 } }
            },
            ["Bone Breaker"] = { level = 8,
                                 enhancements = { [1] = { -0.41, -0.86 }, [2] = { -0.46, 0.5 } }
            },
            ["Immortality"] = { level = 9,
                                enhancements = { [1] = { -0.41, 0.35 }, [2] = { -0.41, 0.56 } }
            },
            ["The Maw of Madness"] = { level = 9,
                                       enhancements = { [1] = { -0.41, -0.92 }, [2] = { -0.53, 0.54 }, [3] = { -0.35, 0.69 } }
            }
        }
    },
    Elementalist = {
        boxGuid = "21d7e7",
        hp = HpProgression.Low,
        perks = {
            [1] = { remove = { "(-1)", "(-1)" } },
            [2] = { remove = { "(-1)", "(-1)" } },
            [3] = { remove = { "(-1)" }, add = { "(+1)" } },
            [4] = { remove = { "(+0)" }, add = { "(+2)" } },
            [5] = { remove = { "(+0)" }, add = { "(+2)" } },
            [6] = { add = { "(Fire)", "(Fire)", "(Fire)" } },
            [7] = { add = { "(Ice)", "(Ice)", "(Ice)" } },
            [8] = { add = { "(Air)", "(Air)", "(Air)" } },
            [9] = { add = { "(Earth)", "(Earth)", "(Earth)" } },
            [10] = { remove = { "(+0)", "(+0)" }, add = { "(Fire)", "(Earth)" } },
            [11] = { remove = { "(+0)", "(+0)" }, add = { "(Ice)", "(Air)" } },
            [12] = { add = { "(+1) (Push 1)", "(+1) (Push 1)" } },
            [13] = { add = { "(+1) (Wound)" } },
            [14] = { add = { "(Stun)" } },
            [15] = { add = { "(Add Target)" } }
        },
        abilities = {
            ["Formless Power"] = { level = 1,
                                   enhancements = { [1] = { -0.41, -0.93 }, [2] = { -0.34, -0.73 } }
            },
            ["Infernal Vortex"] = { level = 1,
                                    enhancements = { [2] = { -0.66, -0.78 }, [1] = { -0.46, -0.78 }, [3] = { -0.41, 0.64 } }
            },
            ["Frigid Torrent"] = { level = 1,
                                   enhancements = { [1] = { -0.46, -0.68 }, [2] = { -0.15, 0.5 }, [3] = { -0.03, 0.8 }, [4] = { -0.33, 0.64 } }
            },
            ["Ice Spikes"] = { level = 1,
                               enhancements = { [1] = { -0.17, -0.83 }, [2] = { -0.41, -0.67 }, [3] = { -0.46, 0.5 }, [4] = { -0.33, 0.65 } }
            },
            ["Pure Augmentation"] = { level = 1,
                                      enhancements = { [1] = { -0.41, -0.92 }, [2] = { -0.41, 0.51 } }
            },
            ["Tremulant Cyclone"] = { level = 1,
                                      enhancements = { [1] = { -0.12, -0.82 }, [2] = { -0.41, 0.65 } }
            },
            ["Land Eruption"] = { level = 1,
                                  enhancements = { [1] = { -0.41, -0.77 }, [2] = { -0.41, 0.63 } }
            },
            ["Shaping the Ether"] = { level = 1,
                                      enhancements = { [1] = { -0.41, -0.95 } }
            },
            ["Raw Enhancement"] = { level = 1,
                                    enhancements = { [1] = { -0.46, -0.91 }, [2] = { -0.41, 0.51 } }
            },
            ["Stoking Hail"] = { level = 1,
                                 enhancements = { [1] = { -0.46, -0.75 }, [2] = { -0.33, -0.57 }, [3] = { -0.46, 0.65 } }
            },
            ["Brilliant Flash"] = { level = "X",
                                    enhancements = { [1] = { -0.41, -0.79 }, [2] = { -0.58, -0.79 } }
            },
            ["Encompassing Shadow"] = { level = "X",
                                        enhancements = { [1] = { -0.41, 0.44 } }
            },
            ["Malleable Evocation"] = { level = "X",
                                        enhancements = { [1] = { -0.46, -0.97 }, [2] = { -0.34, -0.79 }, [3] = { -0.41, 0.46 } }
            },
            ["Boiling Arc"] = { level = 2,
                                enhancements = { [1] = { -0.02, -0.68 }, [2] = { -0.41, 0.61 } }
            },
            ["Crystallizing Blast"] = { level = 2,
                                        enhancements = { [1] = { 0.01, -0.79 }, [2] = { 0.1, -0.6 }, [3] = { -0.41, 0.59 } }
            },
            ["Burial"] = { level = 3,
                           enhancements = { [1] = { -0.19, -0.95 }, [2] = { -0.46, 0.57 } }
            },
            ["Chain Lightning"] = { level = 3,
                                    enhancements = { [1] = { -0.51, -1.01 }, [2] = { -0.41, 0.56 } }
            },
            ["Primal Duality"] = { level = 4,
                                   enhancements = { [1] = { -0.46, -0.86 }, [2] = { -0.66, -0.86 }, [3] = { -0.36, -0.54 }, [4] = { -0.41, 0.66 } }
            },
            ["Gravel Vortex"] = { level = 4,
                                  enhancements = { [1] = { -0.41, -0.79 } }
            },
            ["Obsidian Shards"] = { level = 5,
                                    enhancements = { [1] = { -0.46, -0.85 }, [2] = { -0.41, 0.42 } }
            },
            ["Winter's Edge"] = { level = 5,
                                  enhancements = { [1] = { -0.46, -0.8 }, [2] = { -0.41, 0.51 }, [3] = { -0.34, 0.71 } }
            },
            ["Eye of the Hurricane"] = { level = 6,
                                         enhancements = { [1] = { -0.41, -0.99 }, [2] = { -0.41, -0.68 }, [3] = { -0.41, 0.53 } }
            },
            ["Simulacrum"] = { level = 6,
                               enhancements = { [1] = { -0.46, -0.97 }, [3] = { 0.16, 0.67 }, [4] = { -0.27, 0.67 } }
            },
            ["Vengeance"] = { level = 7,
                              enhancements = { [1] = { -0.48, -0.67 }, [2] = { -0.41, 0.38 }, [3] = { -0.5, 0.59 } }
            },
            ["Pragmatic Reinforcement"] = { level = 7,
                                            enhancements = { [1] = { -0.41, -0.95 }, [2] = { -0.41, 0.45 } }
            },
            ["Volatile Consumption"] = { level = 8,
                                         enhancements = { [1] = { -0.41, 0.38 } }
            },
            ["Elemental Aegis"] = { level = 8,
                                    enhancements = { [1] = { -0.41, -0.89 }, [2] = { -0.41, 0.57 }, [3] = { -0.61, 0.57 } }
            },
            ["Ethereal Manifestation"] = { level = 9,
                                           enhancements = { [1] = { 0.19, -0.73 }, [2] = { -0.26, -0.73 }, [3] = { -0.27, -0.53 } }
            },
            ["Eternal Equilibrium"] = { level = 9,
                                        enhancements = { [1] = { -0.46, -0.9 }, [2] = { -0.41, 0.47 } }
            },
        }
    },
    Quartermaster = {
        boxGuid = "d221fc",
        hp = HpProgression.High,
        perks = {
            [1] = { remove = { "(-1)", "(-1)" } },
            [2] = { remove = { "(-1)", "(-1)" } },
            [3] = { remove = { "(+0)", "(+0)", "(+0)", "(+0)" } },
            [4] = { remove = { "(+0)" }, add = { "(+2)" } },
            [5] = { remove = { "(+0)" }, add = { "(+2)" } },
            [6] = { add = { "(+1) (Rolling)", "(+1) (Rolling)" } },
            [7] = { add = { "(+1) (Rolling)", "(+1) (Rolling)" } },
            [8] = { add = { "(Muddle) (Rolling)", "(Muddle) (Rolling)", "(Muddle) (Rolling)" } },
            [9] = { add = { "(Pierce 3) (Rolling)", "(Pierce 3) (Rolling)" } },
            [10] = { add = { "(Stun) (Rolling)" } },
            [11] = { add = { "(Add Target) (Rolling)" } },
            [12] = { add = { "(Refresh)" } },
            [13] = { add = { "(Refresh)" } },
            [14] = { add = { "(Refresh)" } },
            [15] = { ignore = "I", add = { "(+1)", "(+1)" } }
        },
        abilities = {
            ["Oversized Pack"] = { level = 1,
                                   enhancements = {}
            },
            ["Sharpening Kit"] = { level = 1,
                                   enhancements = { [1] = { -0.36, -0.8 } }
            },
            ["Impaling Spear"] = { level = 1,
                                   enhancements = { [1] = { -0.64, -0.96 }, [2] = { -0.41, 0.72 } }
            },
            ["Cleaving Axe"] = { level = 1,
                                 enhancements = { [1] = { -0.25, -0.79 }, [2] = { -0.41, 0.73 } }
            },
            ["Crippling Bow"] = { level = 1,
                                  enhancements = { [1] = { -0.46, 0.61 } }
            },
            ["Hastened Step"] = { level = 1,
                                  enhancements = { [1] = { -0.41, -0.58 }, [2] = { -0.41, 0.73 } }
            },
            ["Iron Bulwark"] = { level = 1,
                                 enhancements = { [1] = { -0.41, 0.55 } }
            },
            ["Restock"] = { level = 1,
                            enhancements = { [1] = { -0.41, 0.71 } }
            },
            ["Proficiency"] = { level = 1,
                                enhancements = { [1] = { -0.41, 0.77 } }
            },
            ["Crushing Hammer"] = { level = "X",
                                    enhancements = { [1] = { -0.41, -0.8 }, [2] = { -0.61, -0.8 }, [3] = { -0.41, 0.69 } }
            },
            ["Reserved Energy"] = { level = "X",
                                    enhancements = { [1] = { -0.41, 0.73 } }
            },
            ["Scroll of Recall"] = { level = "X",
                                     enhancements = { [1] = { -0.41, 0.63 }, [2] = { -0.33, 0.92 } }
            },
            ["Bladed Boomerang"] = { level = 2,
                                     enhancements = { [1] = { -0.41, 0.77 } }
            },
            ["Reforge"] = { level = 2,
                            enhancements = {}
            },
            ["Scroll of Lightning"] = { level = 3,
                                        enhancements = { [1] = { -0.41, 0.44 }, [2] = { -0.41, 0.68 } }
            },
            ["Continual Supply"] = { level = 3,
                                     enhancements = {}
            },
            ["Giant Club"] = { level = 4,
                               enhancements = { [1] = { -0.46, 0.7 } }
            },
            ["Side Pouch"] = { level = 4,
                               enhancements = { [1] = { -0.41, 0.63 } }
            },
            ["Scroll of Judgement"] = { level = 5,
                                        enhancements = { [1] = { -0.41, 0.56 }, [2] = { -0.41, 0.81 } }
            },
            ["Reinforced Steel"] = { level = 5,
                                     enhancements = { [1] = { -0.41, 0.54 } }
            },
            ["Catastrophic Bomb"] = { level = 6,
                                      enhancements = { [1] = { -0.23, -1.01 }, [2] = { -0.46, -1 } }
            },
            ["Quiver of Arrows"] = { level = 6,
                                     enhancements = { [1] = { -0.41, 0.75 } }
            },
            ["Refreshments"] = { level = 7,
                                 enhancements = {}
            },
            ["Scroll of Blizzards"] = { level = 7,
                                        enhancements = { [1] = { 0.06, -0.82 }, [3] = { -0.51, -1.08 }, [2] = { -0.21, -0.15 }, [4] = { -0.58, 0.42 }, [5] = { -0.41, 0.81 } }
            },
            ["Fortified Position"] = { level = 8,
                                       enhancements = { [1] = { -0.41, 0.44 }, [2] = { -0.41, 0.67 } }
            },
            ["Portable Balliswta"] = { level = 8,
                                       enhancements = { [1] = { 0.02, -0.7 }, [2] = { -0.12, -0.8 }, [3] = { -0.46, -1.02 } }
            },
            ["Bag of Holding"] = { level = 9,
                                   enhancements = {}
            },
            ["Scroll of Annihilation"] = { level = 9,
                                           enhancements = { [1] = { -0.41, 0.56 }, [2] = { -0.46, 0.79 } }
            }
        }
    },
    ["Beast Tyrant"] = {
        boxGuid = "89bec7",
        hp = HpProgression.Low,
        extra = {
            {
                type = "Figurine",
                name = "Bear Companion",
                hp = HpProgression.High,
            },
            {
                type = "Card",
                name = "Beast Tyrant Special Rules",
            }
        },
        perks = {
            [1] = { remove = { "(-1)", "(-1)" } },
            [2] = { remove = { "(-1)" }, add = { "(+1)" } },
            [3] = { remove = { "(-1)" }, add = { "(+1)" } },
            [4] = { remove = { "(-1)" }, add = { "(+1)" } },
            [5] = { remove = { "(+0)" }, add = { "(+2)" } },
            [6] = { remove = { "(+0)" }, add = { "(+2)" } },
            [7] = { add = { "(+1) (Wound)" } },
            [8] = { add = { "(+1) (Wound)" } },
            [9] = { add = { "(+1) (Immobilize)" } },
            [10] = { add = { "(+1) (Immobilize)" } },
            [11] = { add = { "(Heal +1 Self) (Rolling)", "(Heal +1 Self) (Rolling)" } },
            [12] = { add = { "(Heal +1 Self) (Rolling)", "(Heal +1 Self) (Rolling)" } },
            [13] = { add = { "(Heal +1 Self) (Rolling)", "(Heal +1 Self) (Rolling)" } },
            [14] = { add = { "(Earth) (Rolling)", "(Earth) (Rolling)" } },
            [15] = { ignore = "S" }
        },
        abilities = {
            ["Patch Fur"] = { level = 1,
                              enhancements = { [1] = { -0.37, 0.53 }, [2] = { -0.57, 0.53 } }
            },
            ["Relentless Ally"] = { level = 1,
                                    enhancements = { [1] = { 0.18, -0.76 }, [2] = { -0.26, -0.76 }, [3] = { 0.18, -0.56 }, [4] = { -0.41, 0.73 } }
            },
            ["Maul"] = { level = 1,
                         enhancements = { [1] = { -0.41, -0.59 }, [2] = { -0.61, -0.59 }, [3] = { -0.41, 0.42 } }
            },
            ["Forceful Swipe"] = { level = 1,
                                   enhancements = { [1] = { -0.05, -0.68 }, [2] = { -0.29, -0.79 }, [3] = { -0.41, 0.46 }, [4] = { -0.41, 0.67 } }
            },
            ["Concentrated Rage"] = { level = 1,
                                      enhancements = { [1] = { -0.41, -0.73 }, [2] = { -0.35, -0.56 } }
            },
            ["Venemous Ally"] = { level = 1,
                                  enhancements = { [1] = { 0.19, -0.73 }, [2] = { -0.26, -0.75 }, [3] = { 0.19, -0.52 }, [4] = { -0.35, 0.78 } }
            },
            ["Disorienting Roar"] = { level = 1,
                                      enhancements = {}
            },
            ["Howling Bolts"] = { level = 1,
                                  enhancements = { [1] = { -0.33, -0.47 }, [2] = { -0.41, 0.59 } }
            },
            ["Spirit Swap"] = { level = 1,
                                enhancements = { [1] = { -0.41, -0.72 }, [2] = { -0.61, -0.72 } }
            },
            ["Disappearing Wounds"] = { level = 1,
                                        enhancements = { [1] = { -0.37, -0.65 }, [2] = { -0.46, 0.62 }, [3] = { -0.66, 0.62 } }
            },
            ["Focussed Aggresion"] = { level = "X",
                                       enhancements = { [1] = { -0.31, -0.5 }, [2] = { -0.41, 0.63 }, [3] = { -0.61, 0.63 } }
            },
            ["Soaring Ally"] = { level = "X",
                                 enhancements = { [1] = { 0.22, -0.73 }, [2] = { -0.23, -0.73 } }
            },
            ["Borrowed Essence"] = { level = "X",
                                     enhancements = { [1] = { -0.41, -1 }, [2] = { -0.35, -0.46 } }
            },
            ["Energizing Strike"] = { level = 2,
                                      enhancements = { [1] = { -0.41, -0.9 }, [2] = { -0.61, -0.9 } }
            },
            ["Earthen Spikes"] = { level = 2,
                                   enhancements = { [1] = { -0.31, -0.7 } }
            },
            ["Vicious Ally"] = { level = 3,
                                 enhancements = { [1] = { 0.21, -0.71 }, [2] = { -0.24, -0.72 }, [3] = { 0.21, -0.53 }, [4] = { -0.41, 0.56 }, [5] = { -0.31, 0.76 } }
            },
            ["Unstoppable Beast"] = { level = 3,
                                      enhancements = { [1] = { -0.14, -0.67 }, [2] = { -0.34, -0.78 }, [3] = { -0.41, 0.74 } }
            },
            ["Ancient Ward"] = { level = 4,
                                 enhancements = { [1] = { -0.41, -0.92 }, [2] = { -0.32, -0.6 }, [3] = { -0.37, 0.71 } }
            },
            ["Punch Through"] = { level = 4,
                                  enhancements = { [1] = { -0.41, -0.75 }, [2] = { -0.34, -0.59 }, [3] = { -0.41, 0.46 } }
            },
            ["Stone Sigil"] = { level = 5,
                                enhancements = { [1] = { -0.41, 0.73 }, [2] = { -0.58, 0.73 } }
            },
            ["Rampage"] = { level = 5,
                            enhancements = { [1] = { -0.41, -0.75 }, [2] = { -0.41, -0.39 } }
            },
            ["Primal Blessing"] = { level = 6,
                                    enhancements = { [1] = { -0.32, -0.55 }, [2] = { -0.41, 0.5 }, [3] = { -0.41, 1 } }
            },
            ["Blood Hunger"] = { level = 6,
                                 enhancements = { [1] = { -0.41, 0.53 }, [2] = { -0.36, 0.77 } }
            },
            ["Storm Sigil"] = { level = 7,
                                enhancements = { [1] = { -0.41, 0.78 }, [2] = { -0.61, 0.78 } }
            },
            ["Tyrannical Force"] = { level = 7,
                                     enhancements = { [1] = { -0.32, -0.69 } }
            },
            ["Lash out"] = { level = 8,
                             enhancements = { [1] = { -0.41, -0.76 }, [2] = { -0.37, 0.5 }, [3] = { -0.41, 0.69 } }
            },
            ["Natural Remedy"] = { level = 8,
                                   enhancements = { [1] = { -0.37, -0.72 }, [2] = { -0.41, 0.58 } }
            },
            ["Tribal Sigil"] = { level = 9,
                                 enhancements = {}
            },
            ["Jaws of Death"] = { level = 9,
                                  enhancements = { [1] = { -0.41, 0.5 }, [2] = { -0.41, 1.09 } }
            }
        }
    },
    Soothsinger = {
        boxGuid = "732351",
        hp = HpProgression.Low,
        perks = {
            [1] = { remove = { "(-1)", "(-1)" } },
            [2] = { remove = { "(-1)", "(-1)" } },
            [3] = { remove = { "(-2)" } },
            [4] = { remove = { "(+1)", "(+1)" }, add = { "(+4)" } },
            [5] = { remove = { "(+1)", "(+1)" }, add = { "(+4)" } },
            [6] = { remove = { "(+0)" }, add = { "(+1) (Immobilize)" } },
            [7] = { remove = { "(+0)" }, add = { "(+1) (Disarm)" } },
            [8] = { remove = { "(+0)" }, add = { "(+2) (Wound)" } },
            [9] = { remove = { "(+0)" }, add = { "(+2) (Poison)" } },
            [10] = { remove = { "(+0)" }, add = { "(+2) (Curse)" } },
            [11] = { remove = { "(+0)" }, add = { "(+3) (Muddle)" } },
            [12] = { remove = { "(-1)" }, add = { "(Stun)" } },
            [13] = { add = { "(+1) (Rolling)", "(+1) (Rolling)", "(+1) (Rolling)" } },
            [14] = { add = { "(Curse) (Rolling)", "(Curse) (Rolling)" } },
            [15] = { add = { "(Curse) (Rolling)", "(Curse) (Rolling)" } }
        },
        abilities = {
            ["Singing Arrow"] = { level = 1,
                                  enhancements = { [1] = { -0.26, -0.69 }, [2] = { -0.41, 0.61 }, [3] = { -0.34, 0.80 } }
            },
            ["Warding Dagger"] = { level = 1,
                                   enhancements = { [1] = { -0.41, -0.63 }, [2] = { -0.41, 0.43 }, [3] = { -0.41, 0.64 } }
            },
            ["Tuning the Outcome"] = { level = 1,
                                       enhancements = { [1] = { -0.41, -0.63 }, [2] = { -0.41, 0.55 }, [3] = { -0.41, 0.81 } }
            },
            ["Marching Beat"] = { level = 1,
                                  enhancements = { [1] = { -0.41, -0.49 }, [2] = { -0.41, 0.75 } }
            },
            ["Song of Speed"] = { level = 1,
                                  enhancements = {}
            },
            ["Call to Action"] = { level = 1,
                                   enhancements = { [1] = { -0.41, 0.81 } }
            },
            ["Power Ballad"] = { level = 1,
                                 enhancements = { [1] = { -0.41, 0.43 }, [2] = { -0.61, 0.69 } }
            },
            ["Defensive Ditty"] = { level = 1,
                                    enhancements = {}
            },
            ["Throw Voice"] = { level = 1,
                                enhancements = { [1] = { -0.25, -0.72 }, [2] = { -0.41, 0.59 } }
            },
            ["Nimble Knife"] = { level = "X",
                                 enhancements = { [1] = { -0.41, -0.84 }, [2] = { -0.41, -0.43 }, [3] = { -0.41, 0.73 } }
            },
            ["Unending Chant"] = { level = "X",
                                   enhancements = { [1] = { -0.41, 0.67 } }
            },
            ["Wistful Wounding"] = { level = "X",
                                     enhancements = { [1] = { -0.32, 0.58 } }
            },
            ["Soothing Lullaby"] = { level = 2,
                                     enhancements = { [1] = { -0.36, 0.55 } }
            },
            ["Change Tempo"] = { level = 2,
                                 enhancements = { [1] = { -0.41, 0.73 } }
            },
            ["Echoing Aria"] = { level = 3,
                                 enhancements = {}
            },
            ["Crippling Chrous"] = { level = 3,
                                     enhancements = { [1] = { -0.41, -0.78 }, [2] = { -0.41, 0.57 }, [3] = { -0.46, 0.8 } }
            },
            ["Disorienting Dirge"] = { level = 4,
                                       enhancements = { [1] = { -0.41, 0.37 }, [2] = { -0.41, 0.76 } }
            },
            ["Inspiring Anthem"] = { level = 4,
                                     enhancements = { [1] = { -0.37, -0.5 }, [2] = { -0.41, 0.83 } }
            },
            ["Melody and Harmony"] = { level = 5,
                                       enhancements = { [1] = { -0.41, 0.55 }, [2] = { -0.41, 0.81 } }
            },
            ["Mobilizing Measure"] = { level = 5,
                                       enhancements = { [1] = { -0.41, 0.61 } }
            },
            ["Pull the Strings"] = { level = 6,
                                     enhancements = {}
            },
            ["Provoke Terror"] = { level = 6,
                                   enhancements = { [1] = { -0.25, -0.71 }, [2] = { -0.41, 0.59 }, [3] = { -0.33, 0.91 } }
            },
            ["Nightmare Serenade"] = { level = 7,
                                       enhancements = { [1] = { -0.06, 0.49 }, [2] = { -0.27, 0.6 } }
            },
            ["Booming Proclamation"] = { level = 7,
                                         enhancements = { [1] = { -0.41, -0.72 }, [2] = { -0.32, -0.39 }, [3] = { -0.41, 0.71 } }
            },
            ["Tranquil Trill"] = { level = 8,
                                   enhancements = { [1] = { -0.46, 0.56 } }
            },
            ["Commanding Presence"] = { level = 8,
                                        enhancements = { [1] = { -0.41, -0.58 } }
            },
            ["Captivating Performance"] = { level = 9,
                                            enhancements = { [1] = { -0.41, 0.5 }, [2] = { -0.34, 0.78 } }
            },
            ["Shadow Puppets"] = { level = 9,
                                   enhancements = { [1] = { -0.41, -0.95 } }
            }
        }
    },
    Plagueherald = {
        boxGuid = "10b86a",
        hp = HpProgression.Low,
        perks = {
            [1] = { remove = { "(-2)" }, add = { "(+0)" } },
            [2] = { remove = { "(-1)" }, add = { "(+1)" } },
            [3] = { remove = { "(-1)" }, add = { "(+1)" } },
            [4] = { remove = { "(+0)" }, add = { "(+2)" } },
            [5] = { remove = { "(+0)" }, add = { "(+2)" } },
            [6] = { add = { "(+1)", "(+1)" } },
            [7] = { add = { "(+1) (Air)" } },
            [8] = { add = { "(+1) (Air)" } },
            [9] = { add = { "(+1) (Air)" } },
            [10] = { add = { "(Poison) (Rolling)", "(Poison) (Rolling)", "(Poison) (Rolling)" } },
            [11] = { add = { "(Curse) (Rolling)", "(Curse) (Rolling)" } },
            [12] = { add = { "(Immobilize) (Rolling)", "(Immobilize) (Rolling)" } },
            [13] = { add = { "(Stun) (Rolling)" } },
            [14] = { add = { "(Stun) (Rolling)" } },
            [15] = { ignore = "S", add = { "(+1)" } }
        },
        abilities = {
            ["Biting Gnats"] = { level = 1,
                                 enhancements = { [1] = { -0.41, -0.86 }, [2] = { -0.33, -0.56 }, [3] = { -0.41, 0.77 } }
            },
            ["Scattered Terror"] = { level = 1,
                                     enhancements = { [1] = { -0.46, -0.92 }, [2] = { -0.34, -0.77 }, [3] = { -0.32, -0.62 }, [4] = { -0.36, -0.46 } }
            },
            ["Grasping Vermin"] = { level = 1,
                                    enhancements = {}
            },
            ["Foul Wind"] = { level = 1,
                              enhancements = {}
            },
            ["Wretched Swarm"] = { level = 1,
                                   enhancements = { [1] = { 0.03, -0.88 }, [2] = { -0.41, 0.75 } }
            },
            ["Gathering Doom"] = { level = 1,
                                   enhancements = { [1] = { -0.41, -0.72 } }
            },
            ["Vile Pestilence"] = { level = 1,
                                    enhancements = { [1] = { -0.41, 0.75 } }
            },
            ["Winged Congregation"] = { level = 1,
                                        enhancements = { [1] = { -0.41, 0.57 }, [2] = { -0.37, 0.83 } }
            },
            ["Creeping Curse"] = { level = 1,
                                   enhancements = { [1] = { -0.41, -0.73 }, [2] = { -0.41, 0.58 }, [3] = { -0.41, 0.83 } }
            },
            ["Spread the Plague"] = { level = 1,
                                      enhancements = { [1] = { -0.41, 0.69 }, [2] = { -0.33, 0.86 } }
            },
            ["Paralyzing Bite"] = { level = 1,
                                    enhancements = { [1] = { -0.41, -0.84 }, [2] = { -0.41, 0.57 } }
            },
            ["Virulent Strain"] = { level = "X",
                                    enhancements = {}
            },
            ["Blistering Vortex"] = { level = "X",
                                      enhancements = { [1] = { -0.08, -0.8 }, [2] = { -0.29, -0.68 }, [3] = { -0.41, 0.46 }, [4] = { -0.41, 0.71 } }
            },
            ["Epidemic"] = { level = "X",
                             enhancements = { [1] = { -0.41, -0.85 }, [2] = { -0.34, -0.54 } }
            },
            ["Rot Maggots"] = { level = 2,
                                enhancements = { [1] = { -0.41, -0.94 }, [2] = { -0.34, 0.77 }, [3] = { -0.33, 0.96 } }
            },
            ["Under the Skin"] = { level = 2,
                                   enhancements = { [1] = { -0.41, -0.85 }, [2] = { -0.61, -0.85 }, [3] = { -0.41, 0.74 } }
            },
            ["Fetid Flurry"] = { level = 3,
                                 enhancements = { [1] = { -0.41, -0.72 }, [2] = { -0.41, 0.64 } }
            },
            ["Succumb to the Gift"] = { level = 3,
                                        enhancements = { [1] = { -0.41, 0.72 } }
            },
            ["Nightmarish Affliction"] = { level = 4,
                                           enhancements = { [1] = { -0.41, -0.98 }, [2] = { -0.33, -0.67 }, [3] = { -0.34, 0.94 } }
            },
            ["Storm of Wings"] = { level = 4,
                                   enhancements = { [1] = { -0.41, 0.76 } }
            },
            ["Accelerated End"] = { level = 5,
                                    enhancements = { [1] = { -0.33, 0.94 } }
            },
            ["Willing Sacrifice"] = { level = 5,
                                      enhancements = {}
            },
            ["Black Tides"] = { level = 6,
                                enhancements = { [1] = { -0.46, -0.8 }, [2] = { -0.66, -0.8 }, [3] = { -0.34, -0.61 }, [4] = { -0.41, 0.65 } }
            },
            ["Stinging Cloud"] = { level = 6,
                                   enhancements = { [1] = { -0.41, 0.46 }, [2] = { -0.41, 0.72 } }
            },
            ["Airborne Toxin"] = { level = 7,
                                   enhancements = {}
            },
            ["Baneful Hex"] = { level = 7,
                                enhancements = { [1] = { -0.41, 0.83 } }
            },
            ["Grim Bargain"] = { level = 8,
                                 enhancements = {}
            },
            ["Spreading Scrouge"] = { level = 8,
                                      enhancements = { [1] = { -0.22, -0.97 }, [2] = { -0.44, -0.97 }, [3] = { -0.33, 0.78 }, [4] = { -0.34, 0.95 } }
            },
            ["Convert the Flock"] = { level = 9,
                                      enhancements = { [1] = { -0.46, -0.93 }, [2] = { -0.34, -0.76 }, [3] = { -0.34, -0.62 } }
            },
            ["Mass Extinction"] = { level = 9,
                                    enhancements = {}
            }
        }
    },
    Nightshroud = {
        boxGuid = "8f7455",
        hp = HpProgression.Medium,
        perks = {
            [1] = { remove = { "(-1)", "(-1)" } },
            [2] = { remove = { "(-1)", "(-1)" } },
            [3] = { remove = { "(+0)", "(+0)", "(+0)", "(+0)" } },
            [4] = { add = { "(-1) (Dark)" } },
            [5] = { add = { "(-1) (Dark)" } },
            [6] = { remove = { "(-1) (Dark)" }, add = { "(+1) (Dark)" } },
            [7] = { remove = { "(-1) (Dark)" }, add = { "(+1) (Dark)" } },
            [8] = { add = { "(+1) (Invisibility)" } },
            [9] = { add = { "(+1) (Invisibility)" } },
            [10] = { add = { "(Muddle) (Rolling)", "(Muddle) (Rolling)", "(Muddle) (Rolling)" } },
            [11] = { add = { "(Muddle) (Rolling)", "(Muddle) (Rolling)", "(Muddle) (Rolling)" } },
            [12] = { add = { "(Heal 1 Self) (Rolling)", "(Heal 1 Self) (Rolling)" } },
            [13] = { add = { "(Curse) (Rolling)", "(Curse) (Rolling)" } },
            [14] = { add = { "(Add Target) (Rolling)" } },
            [15] = { ignore = "S", add = { "(+1)", "(+1)" } }
        },
        abilities = {
            ["Silent Force"] = { level = 1,
                                 enhancements = { [1] = { -0.41, 0.63 } }
            },
            ["Empowering Void"] = { level = 1,
                                    enhancements = {}
            },
            ["Cloak of Shade"] = { level = 1,
                                   enhancements = { [1] = { -0.41, -0.72 }, [2] = { -0.61, -0.72 } }
            },
            ["Spirit of the Night"] = { level = 1,
                                        enhancements = { [1] = { -0.41, 0.63 }, [2] = { -0.61, 0.63 } }
            },
            ["Enervating Wound"] = { level = 1,
                                     enhancements = { [1] = { -0.41, -0.96 }, [2] = { -0.41, -0.61 } }
            },
            ["Smoke Step"] = { level = 1,
                               enhancements = { [1] = { -0.41, 0.62 }, [2] = { -0.61, 0.62 } }
            },
            ["Doomed Breeze"] = { level = 1,
                                  enhancements = { [1] = { -0.41, -0.85 }, [2] = { -0.32, -0.68 } }
            },
            ["Black Knives"] = { level = 1,
                                 enhancements = {}
            },
            ["Dancing Shadows"] = { level = 1,
                                    enhancements = { [1] = { -0.41, -0.7 } }
            },
            ["Wings of the Night"] = { level = "X",
                                       enhancements = {}
            },
            ["Dark Cloud"] = { level = "X",
                               enhancements = {}
            },
            ["Concealed Dominance"] = { level = "X",
                                        enhancements = {}
            },
            ["Prepare for the Kill"] = { level = 2,
                                         enhancements = { [1] = { -0.41, -0.71 }, [2] = { -0.61, -0.71 }, [3] = { -0.41, 0.63 }, [4] = { -0.61, 0.63 } }
            },
            ["Soulfire"] = { level = 2,
                             enhancements = { [1] = { -0.32, -0.73 }, [2] = { -0.41, 0.68 }, [3] = { -0.61, 0.67 } }
            },
            ["Terror Blade"] = { level = 3,
                                 enhancements = { [1] = { -0.34, -0.51 } }
            },
            ["Armor of the Night"] = { level = 3,
                                       enhancements = { [1] = { -0.41, 0.56 }, [2] = { -0.61, 0.56 } }
            },
            ["Nightfall"] = { level = 4,
                              enhancements = {}
            },
            ["Grim Sustenance"] = { level = 4,
                                    enhancements = {}
            },
            ["Claws of the Night"] = { level = 5,
                                       enhancements = { [1] = { -0.17, -0.77 } }
            },
            ["Black Arrow"] = { level = 5,
                                enhancements = { [1] = { -0.35, -0.76 } }
            },
            ["Unseen Dread"] = { level = 6,
                                 enhancements = { [1] = { -0.41, -0.73 }, [2] = { -0.61, -0.73 }, [3] = { -0.41, 0.66 } }
            },
            ["Swallowed by Fear"] = { level = 6,
                                      enhancements = { [1] = { -0.41, -0.74 } }
            },
            ["Eyes of the Night"] = { level = 7,
                                      enhancements = {}
            },
            ["Quiet Frenzy"] = { level = 7,
                                 enhancements = {}
            },
            ["Gloom Darts"] = { level = 8,
                                enhancements = { [1] = { -0.33, -0.76 }, [2] = { -0.41, 0.62 }, [3] = { -0.61, 0.62 } }
            },
            ["Lurking Ruin"] = { level = 8,
                                 enhancements = {}
            },
            ["Angel of Death"] = { level = 9,
                                   enhancements = { [1] = { -0.41, -0.9 }, [2] = { -0.41, 0.54 } }
            },
            ["Voice of the Night"] = { level = 9,
                                       enhancements = { [1] = { -0.41, 0.53 }, [2] = { -0.41, 0.76 } }
            },
        }
    },
    Sawbones = {
        boxGuid = "e5148c",
        hp = HpProgression.Medium,
        perks = {
            [1] = { remove = { "(-1)", "(-1)" } },
            [2] = { remove = { "(-1)", "(-1)" } },
            [3] = { remove = { "(+0)", "(+0)", "(+0)", "(+0)" } },
            [4] = { remove = { "(+0)" }, add = { "(+2)" } },
            [5] = { remove = { "(+0)" }, add = { "(+2)" } },
            [6] = { add = { "(+2) (Rolling)" } },
            [7] = { add = { "(+2) (Rolling)" } },
            [8] = { add = { "(+1) (Immobilize)" } },
            [9] = { add = { "(+1) (Immobilize)" } },
            [10] = { add = { "(Wound) (Rolling)", "(Wound) (Rolling)" } },
            [11] = { add = { "(Wound) (Rolling)", "(Wound) (Rolling)" } },
            [12] = { add = { "(Stun) (Rolling)" } },
            [13] = { add = { "(Heal 3 Self) (Rolling)" } },
            [14] = { add = { "(Heal 3 Self) (Rolling)" } },
            [15] = { add = { "(Refresh)" } }
        },
        abilities = {
            ["Mobile Response"] = { level = 1,
                                    enhancements = { [1] = { -0.41, 0.41 } }
            },
            ["Battlefield Medicine"] = { level = 1,
                                         enhancements = {}
            },
            ["Syringe"] = { level = 1,
                            enhancements = { [1] = { -0.41, -0.57 }, [2] = { -0.41, 0.6 } }
            },
            ["Hand of the Surgeon"] = { level = 1,
                                        enhancements = { [1] = { -0.41, -0.71 } }
            },
            ["Curative Mixture"] = { level = 1,
                                     enhancements = { [1] = { -0.35, -0.91 }, [2] = { -0.55, -0.91 }, [3] = { -0.41, 0.6 } }
            },
            ["Booster Shot"] = { level = 1,
                                 enhancements = { [1] = { -0.36, -0.64 }, [2] = { -0.57, -0.66 } }
            },
            ["Hold Back the Pain"] = { level = 1,
                                       enhancements = { [1] = { -0.37, -0.77 }, [2] = { -0.57, -0.77 } }
            },
            ["Triage"] = { level = 1,
                           enhancements = { [1] = { -0.41, 0.73 } }
            },
            ["First Aid"] = { level = 1,
                              enhancements = { [1] = { -0.41, 0.75 } }
            },
            ["Bloody Saw"] = { level = 1,
                               enhancements = { [1] = { -0.41, -0.78 } }
            },
            ["Prevention Is Key"] = { level = "X",
                                      enhancements = { [1] = { -0.48, -0.65 }, [2] = { -0.41, 0.56 } }
            },
            ["Teamwork"] = { level = "X",
                             enhancements = { [1] = { -0.41, 0.91 } }
            },
            ["Vaccine"] = { level = "X",
                            enhancements = { [1] = { -0.06, -0.86 } }
            },
            ["Precaution"] = { level = 2,
                               enhancements = { [1] = { -0.41, -0.77 } }
            },
            ["Hamstring"] = { level = 2,
                              enhancements = { [1] = { -0.41, -0.81 }, [2] = { -0.41, 0.56 } }
            },
            ["Regenerative Tissue"] = { level = 3,
                                        enhancements = { [1] = { -0.35, -0.77 }, [2] = { -0.56, -0.77 } }
            },
            ["Vital Strike"] = { level = 3,
                                 enhancements = { [1] = { -0.41, -0.72 }, [2] = { -0.61, -0.72 }, [3] = { -0.41, 0.72 } }
            },
            ["Blood Transfusion"] = { level = 4,
                                      enhancements = { [1] = { -0.37, -0.93 }, [2] = { -0.41, 0.54 }, [3] = { -0.41, 0.8 } }
            },
            ["Do No Harm"] = { level = 4,
                               enhancements = { [1] = { -0.37, 0.81 }, [2] = { -0.57, 0.81 } }
            },
            ["Amputate"] = { level = 5,
                             enhancements = { [1] = { -0.41, -0.86 }, [2] = { -0.41, 0.6 }, [3] = { -0.61, 0.6 } }
            },
            ["Research the Cure"] = { level = 5,
                                      enhancements = { [1] = { -0.41, -0.77 } }
            },
            ["Prescription"] = { level = 6,
                                 enhancements = {}
            },
            ["Euthanize"] = { level = 6,
                              enhancements = { [1] = { -0.41, 0.54 } }
            },
            ["Master Physician"] = { level = 7,
                                     enhancements = {}
            },
            ["Surgeon's Satchel"] = { level = 7,
                                      enhancements = { [1] = { -0.36, -0.56 }, [2] = { -0.41, 0.45 } }
            },
            ["Gentleman's Anger"] = { level = 8,
                                      enhancements = { [1] = { -0.41, -0.8 }, [2] = { -0.46, 0.54 } }
            },
            ["Bedside Manner"] = { level = 8,
                                   enhancements = { [1] = { -0.35, -1.02 }, [2] = { -0.55, -1.02 }, [3] = { -0.41, 0.57 } }
            },
            ["Prep for Surgery"] = { level = 9,
                                     enhancements = { [1] = { -0.41, 0.56 }, [2] = { -0.41, 0.84 } }
            },
            ["Grisley Trauma"] = { level = 9,
                                   enhancements = { [1] = { -0.41, 0.47 } }
            },
        }
    },
    Sunkeeper = {
        boxGuid = "bfe08d",
        hp = HpProgression.High,
        perks = {
            [1] = { remove = { "(-1)", "(-1)" } },
            [2] = { remove = { "(-1)", "(-1)" } },
            [3] = { remove = { "(+0)", "(+0)", "(+0)", "(+0)" } },
            [4] = { remove = { "(-2)" }, add = { "(+0)" } },
            [5] = { remove = { "(+0)" }, add = { "(+2)" } },
            [6] = { add = { "(+1) (Rolling)", "(+1) (Rolling)" } },
            [7] = { add = { "(+1) (Rolling)", "(+1) (Rolling)" } },
            [8] = { add = { "(Heal 1 Self) (Rolling)", "(Heal 1 Self) (Rolling)" } },
            [9] = { add = { "(Heal 1 Self) (Rolling)", "(Heal 1 Self) (Rolling)" } },
            [10] = { add = { "(Stun) (Rolling)" } },
            [11] = { add = { "(Light) (Rolling)", "(Light) (Rolling)" } },
            [12] = { add = { "(Light) (Rolling)", "(Light) (Rolling)" } },
            [13] = { add = { "(Shield 1 Self) (Rolling)", "(Shield 1 Self) (Rolling)" } },
            [14] = { ignore = "I", add = { "(+1)", "(+1)" } },
            [15] = { ignore = "S" }
        },
        abilities = {
            ["Lay on Hands"] = { level = 1,
                                 enhancements = {}
            },
            ["Tactical Order"] = { level = 1,
                                   enhancements = { [1] = { -0.41, -0.5 }, [2] = { -0.41, 0.77 } }
            },
            ["Purifying Aura"] = { level = 1,
                                   enhancements = { [1] = { -0.61, 0.57 } }
            },
            ["Holy Strike"] = { level = 1,
                                enhancements = { [1] = { -0.46, -0.65 }, [2] = { -0.46, 0.54 }, [3] = { -0.33, 0.71 } }
            },
            ["Empowering Command"] = { level = 1,
                                       enhancements = { [1] = { -0.41, 0.82 } }
            },
            ["Hammer Blow"] = { level = 1,
                                enhancements = { [1] = { -0.41, -0.7 }, [2] = { -0.41, 0.74 } }
            },
            ["Protective Blessing"] = { level = 1,
                                        enhancements = {}
            },
            ["Defensive Stance"] = { level = 1,
                                     enhancements = { [1] = { -0.41, -0.7 }, [2] = { -0.41, 0.44 } }
            },
            ["Cautious Advance"] = { level = 1,
                                     enhancements = { [1] = { -0.41, -0.8 }, [2] = { -0.41, 0.74 } }
            },
            ["Brilliant Prayer"] = { level = 1,
                                     enhancements = { [1] = { -0.37, 0.54 }, [2] = { -0.56, 0.54 } }
            },
            ["Dazzling Charge"] = { level = 1,
                                    enhancements = { [1] = { -0.41, -0.78 }, [2] = { -0.41, 0.44 }, [3] = { -0.41, 0.66 } }
            },
            ["Daybreak"] = { level = "X",
                             enhancements = { [1] = { -0.41, -0.78 }, [2] = { -0.41, 0.54 }, [3] = { -0.41, 0.83 } }
            },
            ["Glorious Bolt"] = { level = "X",
                                  enhancements = { [1] = { -0.37, -0.89 }, [2] = { -0.56, -0.89 }, [3] = { -0.46, 0.61 } }
            },
            ["Beacon of Light"] = { level = "X",
                                    enhancements = {}
            },
            ["Practical Plans"] = { level = 2,
                                    enhancements = {}
            },
            ["Unwavering Mandate"] = { level = 2,
                                       enhancements = { [1] = { -0.37, 0.57 }, [2] = { -0.34, 0.74 } }
            },
            ["Burning Flash"] = { level = 3,
                                  enhancements = { [1] = { -0.41, -0.86 }, [2] = { -0.41, 0.54 }, [3] = { -0.33, 0.74 } }
            },
            ["Mobilizing Axiom"] = { level = 3,
                                     enhancements = { [1] = { -0.41, -0.71 } }
            },
            ["Righteous Strength"] = { level = 4,
                                       enhancements = { [1] = { -0.41, -0.79 }, [2] = { -0.41, 0.45 }, [3] = { -0.41, 0.67 } }
            },
            ["Engulfing Radiance"] = { level = 4,
                                       enhancements = { [1] = { -0.35, -0.79 } }
            },
            ["Path of Glory"] = { level = 5,
                                  enhancements = { [1] = { -0.41, -0.71 }, [2] = { -0.61, -0.71 }, [3] = { -0.41, 0.43 } }
            },
            ["Scales of Justice"] = { level = 5,
                                      enhancements = { [1] = { -0.48, -0.91 }, [2] = { -0.41, 0.44 }, [3] = { -0.41, 0.92 } }
            },
            ["Supportive Chant"] = { level = 6,
                                     enhancements = {}
            },
            ["Illuminate the Target"] = { level = 6,
                                          enhancements = { [1] = { -0.41, -0.91 }, [2] = { -0.61, -0.69 }, [3] = { -0.41, 0.83 } }
            },
            ["Weapon of Purity"] = { level = 7,
                                     enhancements = { [1] = { -0.41, 0.64 }, [2] = { -0.41, 0.9 } }
            },
            ["Bright Aegis"] = { level = 7,
                                 enhancements = { [1] = { -0.41, -0.94 }, [2] = { -0.5, -0.6 } }
            },
            ["Cleansing Force"] = { level = 8,
                                    enhancements = { [1] = { -0.41, -0.85 }, [2] = { -0.61, -0.85 }, [3] = { -0.41, 0.62 } }
            },
            ["Inspiring Sanctity"] = { level = 8,
                                       enhancements = {}
            },
            ["Angelic Ascension"] = { level = 9,
                                      enhancements = { [1] = { -0.41, 0.68 } }
            },
            ["Divine Intervention"] = { level = 9,
                                        enhancements = { [1] = { -0.41, 0.55 } }
            },
        }
    },
    Summoner = {
        boxGuid = "0f9847",
        hp = HpProgression.Medium,
        perks = {
            [1] = { remove = { "(-1)", "(-1)" } },
            [2] = { remove = { "(-2)" }, add = { "(+0)" } },
            [3] = { remove = { "(-1)" }, add = { "(+1)" } },
            [4] = { remove = { "(-1)" }, add = { "(+1)" } },
            [5] = { remove = { "(-1)" }, add = { "(+1)" } },
            [6] = { add = { "(+2)" } },
            [7] = { add = { "(+2)" } },
            [8] = { add = { "(Wound) (Rolling)", "(Wound) (Rolling)" } },
            [9] = { add = { "(Poison) (Rolling)", "(Poison) (Rolling)" } },
            [10] = { add = { "(Heal 1 Self) (Rolling)", "(Heal 1 Self) (Rolling)" } },
            [11] = { add = { "(Heal 1 Self) (Rolling)", "(Heal 1 Self) (Rolling)" } },
            [12] = { add = { "(Heal 1 Self) (Rolling)", "(Heal 1 Self) (Rolling)" } },
            [13] = { add = { "(Fire) (Rolling)", "(Air) (Rolling)" } },
            [14] = { add = { "(Dark) (Rolling)", "(Earth) (Rolling)" } },
            [15] = { ignore = "S", add = { "(+1)", "(+1)" } }
        },
        abilities = {
            ["Mighty Bond"] = { level = 1,
                                enhancements = { [1] = { -0.41, 0.7 } }
            },
            ["Biting Wind"] = { level = 1,
                                enhancements = { [1] = { -0.46, -0.77 }, [2] = { -0.34, -0.6 }, [3] = { -0.41, 0.69 } }
            },
            ["Black Fire"] = { level = 1,
                               enhancements = { [1] = { -0.46, -0.84 }, [2] = { -0.36, -0.55 }, [3] = { -0.41, 0.53 } }
            },
            ["Unending Dominance"] = { level = 1,
                                       enhancements = { [1] = { 0.21, -0.72 }, [2] = { -0.25, -0.74 } }
            },
            ["Living Night"] = { level = 1,
                                 enhancements = { [1] = { 0.21, -0.74 }, [2] = { 0.19, -0.53 } }
            },
            ["Unwavering Hand"] = { level = 1,
                                    enhancements = { [1] = { -0.41, -0.8 }, [2] = { -0.61, -0.8 } }
            },
            ["Wild Animation"] = { level = 1,
                                   enhancements = { [1] = { 0.21, -0.73 }, [2] = { -0.25, -0.73 }, [3] = { 0.21, -0.54 }, [4] = { -0.25, -0.54 }, [5] = { -0.41, 0.62 } }
            },
            ["Bonded Might"] = { level = 1,
                                 enhancements = {}
            },
            ["Forged Ferocity"] = { level = 1,
                                    enhancements = { [1] = { 0.21, -0.73 }, [2] = { -0.25, -0.73 }, [3] = { 0.21, -0.54 }, [4] = { -0.41, 0.56 } }
            },
            ["Ethereal Vines"] = { level = "X",
                                   enhancements = { [1] = { -0.09, -0.72 }, [2] = { -0.41, 0.56 }, [3] = { -0.36, 0.83 } }
            },
            ["Leathery Wings"] = { level = "X",
                                   enhancements = { [1] = { 0.21, -0.73 }, [2] = { -0.25, -0.73 }, [3] = { -0.61, 0.66 } }
            },
            ["Volatile Flame"] = { level = "X",
                                   enhancements = { [1] = { -0.25, -0.74 }, [2] = { 0.19, -0.56 }, [3] = { -0.41, 0.53 } }
            },
            ["Earthen Steed"] = { level = 2,
                                  enhancements = { [1] = { -0.41, 0.71 } }
            },
            ["Grasping the Void"] = { level = 2,
                                      enhancements = { [1] = { -0.46, -0.81 }, [2] = { -0.46, 0.51 }, [3] = { -0.41, 0.91 } }
            },
            ["Tear the Fabric"] = { level = 3,
                                    enhancements = { [1] = { -0.41, 0.61 }, [2] = { -0.61, 0.61 } }
            },
            ["Oozing Manifestation"] = { level = 3,
                                         enhancements = { [1] = { 0.21, -0.72 }, [2] = { -0.25, -0.72 }, [3] = { 0.21, -0.51 }, [4] = { -0.46, 0.53 } }
            },
            ["Living Mountain"] = { level = 4,
                                    enhancements = { [1] = { 0.21, -0.72 }, [2] = { -0.25, -0.72 }, [3] = { -0.46, 0.64 } }
            },
            ["Divided Mind"] = { level = 4,
                                 enhancements = {}
            },
            ["Strength in Numbers"] = { level = 5,
                                        enhancements = {}
            },
            ["Conjured Aid"] = { level = 5,
                                 enhancements = { [1] = { 0.21, -0.72 }, [2] = { -0.25, -0.72 }, [3] = { -0.25, -0.51 }, [4] = { -0.41, 0.77 } }
            },
            ["Endless Spikers"] = { level = 6,
                                    enhancements = { [1] = { 0.21, -0.72 }, [2] = { -0.25, -0.72 } }
            },
            ["Inexorable Momentum"] = { level = 6,
                                        enhancements = { [1] = { -0.41, -0.83 }, [2] = { -0.36, -0.53 }, [3] = { -0.41, 0.56 }, [4] = { -0.41, 1 } }
            },
            ["Staff of Visions"] = { level = 7,
                                     enhancements = { [1] = { -0.41, -0.71 }, [2] = { -0.61, -0.71 }, [3] = { -0.41, 0.58 }, [4] = { -0.64, 0.81 } }
            },
            ["Negative Energy"] = { level = 7,
                                    enhancements = { [1] = { 0.21, -0.73 }, [2] = { -0.25, -0.73 }, [3] = { 0.21, -0.51 }, [4] = { -0.25, -0.51 } }
            },
            ["Intervening Apparitions"] = { level = 8,
                                            enhancements = {}
            },
            ["Otherworldly Rage"] = { level = 8,
                                      enhancements = { [1] = { -0.41, 0.92 } }
            },
            ["Interplanar Mastery"] = { level = 9,
                                        enhancements = { [1] = { -0.41, 0.68 } }
            },
            ["Horned Majesty"] = { level = 9,
                                   enhancements = { [1] = { 0.2, -0.72 }, [2] = { -0.25, -0.72 }, [3] = { 0.18, -0.52 } }
            },
        }
    },
    Doomstalker = {
        boxGuid = "b7fe6d",
        hp = HpProgression.Medium,
        perks = {
            [1] = { remove = { "(-1)", "(-1)" } },
            [2] = { remove = { "(-1)", "(-1)" } },
            [3] = { remove = { "(+0)", "(+0)" }, add = { "(+1)", "(+1)" } },
            [4] = { remove = { "(+0)", "(+0)" }, add = { "(+1)", "(+1)" } },
            [5] = { remove = { "(+0)", "(+0)" }, add = { "(+1)", "(+1)" } },
            [6] = { add = { "(+1) (Rolling)", "(+1) (Rolling)" } },
            [7] = { add = { "(+1) (Rolling)", "(+1) (Rolling)" } },
            [8] = { add = { "(+2) (Muddle)" } },
            [9] = { add = { "(+1) (Poison)" } },
            [10] = { add = { "(+1) (Wound)" } },
            [11] = { add = { "(+1) (Immobilize)" } },
            [12] = { add = { "(Stun)" } },
            [13] = { add = { "(Add Target) (Rolling)" } },
            [14] = { add = { "(Add Target) (Rolling)" } },
            [15] = { ignore = "S" }
        },
        abilities = {
            ["Race to the Grave"] = { level = 1,
                                      enhancements = { [1] = { -0.41, -0.78 }, [2] = { -0.61, -0.78 }, [3] = { -0.32, -0.62 } }
            },
            ["A Moment's Peace"] = { level = 1,
                                     enhancements = { [1] = { -0.41, 0.56 }, [2] = { -0.37, 0.83 } }
            },
            ["Swift Trickery"] = { level = 1,
                                   enhancements = { [1] = { -0.41, -0.8 }, [2] = { -0.3, -0.62 }, [3] = { -0.41, 0.74 } }
            },
            ["Foot Snare"] = { level = 1,
                               enhancements = { [1] = { -0.41, 0.96 } }
            },
            ["Detonation"] = { level = 1,
                               enhancements = {}
            },
            ["Multi-Pronged Assault"] = { level = 1,
                                          enhancements = { [1] = { -0.41, -0.86 }, [2] = { -0.32, -0.7 }, [3] = { -0.33, -0.52 } }
            },
            ["Frightening Curse"] = { level = 1,
                                      enhancements = {}
            },
            ["Vital Charge"] = { level = 1,
                                 enhancements = { [1] = { 0.2, -0.71 }, [2] = { -0.25, -0.71 }, [3] = { 0.19, -0.51 } }
            },
            ["Feeling Swoop"] = { level = 1,
                                  enhancements = { [1] = { 0.2, -0.73 }, [2] = { -0.23, -0.73 }, [3] = { 0.2, -0.52 } }
            },
            ["Crippling Noose"] = { level = 1,
                                    enhancements = {}
            },
            ["Rain of Arrows"] = { level = 1,
                                   enhancements = {}
            },
            ["Solid Bow"] = { level = 1,
                              enhancements = { [1] = { -0.41, -0.66 }, [2] = { -0.32, -0.49 }, [3] = { -0.41, 0.74 } }
            },
            ["Sap Life"] = { level = "X",
                             enhancements = { [1] = { -0.48, -0.79 }, [2] = { -0.32, -0.61 } }
            },
            ["The Hunt Begins"] = { level = "X",
                                    enhancements = { [1] = { 0.2, -0.73 }, [2] = { -0.24, -0.73 }, [3] = { 0.19, -0.52 } }
            },
            ["Fresh Kill"] = { level = "X",
                               enhancements = { [1] = { -0.41, -0.79 }, [2] = { -0.32, -0.62 }, [3] = { -0.41, 0.69 } }
            },
            ["Expose"] = { level = 2,
                           enhancements = {}
            },
            ["Relentless Offensive"] = { level = 2,
                                         enhancements = { [1] = { -0.41, -0.74 }, [2] = { -0.32, -0.42 } }
            },
            ["Darkened Skies"] = { level = 3,
                                   enhancements = { [1] = { -0.41, -0.79 } }
            },
            ["Press the Attack"] = { level = 3,
                                     enhancements = { [1] = { -0.41, -0.8 }, [2] = { -0.33, -0.64 }, [3] = { -0.49, 0.55 } }
            },
            ["Singular Focus"] = { level = 4,
                                   enhancements = {}
            },
            ["Flight of Flame"] = { level = 4,
                                    enhancements = { [1] = { -0.41, 0.69 } }
            },
            ["Inescapable Fate"] = { level = 5,
                                     enhancements = {}
            },
            ["Wild Commad"] = { level = 5,
                                enhancements = { [1] = { -0.41, 0.51 }, [2] = { -0.41, 0.74 } }
            },
            ["Nature's Hunger"] = { level = 6,
                                    enhancements = { [1] = { 0.2, -0.72 }, [2] = { -0.25, -0.72 }, [3] = { 0.21, -0.52 } }
            },
            ["Camouflage"] = { level = 6,
                               enhancements = { [1] = { -0.41, -0.88 }, [2] = { -0.41, 0.56 } }
            },
            ["Impending End"] = { level = 7,
                                  enhancements = { [1] = { -0.41, -0.86 }, [2] = { -0.33, -0.7 } }
            },
            ["Crashing Wave"] = { level = 7,
                                  enhancements = { [1] = { -0.41, -0.86 }, [2] = { -0.41, -0.62 }, [3] = { -0.61, -0.62 } }
            },
            ["Rising Momentum"] = { level = 8,
                                    enhancements = { [1] = { -0.41, -0.89 }, [2] = { -0.31, -0.72 }, [3] = { -0.32, -0.55 } }
            },
            ["Feral Instincts"] = { level = 8,
                                    enhancements = { [1] = { -0.41, -0.83 }, [2] = { -0.41, -0.57 }, [3] = { -0.41, 0.56 }, [4] = { -0.37, 0.82 } }
            },
            ["Predator and Prey"] = { level = 9,
                                      enhancements = { [1] = { 0.2, -0.74 }, [2] = { -0.23, -0.74 }, [3] = { 0.19, -0.52 }, [4] = { -0.24, -0.55 } }
            },
            ["Lead to Slaughter"] = { level = 9,
                                      enhancements = { [1] = { -0.41, -0.88 }, [2] = { -0.35, -0.72 }, [3] = { -0.41, 0.53 } }
            },
        }
    },
    Diviner = {
        boxGuid = "ae2ea4",
        hp = HpProgression.Low,
        extra = {
            {
                name = "Rifts",
                type = "Token",
            }
        },
        perks = {
            [1] = { remove = { "(-1)", "(-1)" } },
            [2] = { remove = { "(-1)", "(-1)" } },
            [3] = { remove = { "(-2)" } },
            [4] = { remove = { "(+1)", "(+1)" }, add = { "(+3) (Shield 1 Self)" } },
            [5] = { remove = { "(+1)", "(+1)" }, add = { "(+3) (Shield 1 Self)" } },
            [6] = { remove = { "(+0)" }, add = { "(+1) (Shield 1 Ally)" } },
            [7] = { remove = { "(+0)" }, add = { "(+2) (Create Dark)" } },
            [8] = { remove = { "(+0)" }, add = { "(+2) (Create Light)" } },
            [9] = { remove = { "(+0)" }, add = { "(+3) (Muddle)" } },
            [10] = { remove = { "(+0)" }, add = { "(+2) (Curse)" } },
            [11] = { remove = { "(+0)" }, add = { "(+2) (Regenerate Self)" } },
            [12] = { remove = { "(-1)" }, add = { "(+1) (Heal 2 Ally)" } },
            [13] = { add = { "(Heal 1 Self) (Rolling)", "(Heal 1 Self) (Rolling)" } },
            [14] = { add = { "(Curse) (Rolling)", "(Curse) (Rolling)" } },
            [15] = { ignore = "S", add = { "(+1)", "(+1)" } }
        },
        abilities = {
            ["Dimensional Transfer"] = { level = 1,
                                         enhancements = { [1] = { -0.61, -0.51 }, [2] = { 0.01, 0.77 } }
            },
            ["Otherworldly Journey"] = { level = 1,
                                         enhancements = { [1] = { 0.01, 0.78 } }
            },
            ["Ray of Light"] = { level = 1,
                                 enhancements = { [1] = { -0.37, -0.78 }, [2] = { -0.56, -0.78 }, [3] = { -0.46, 0.81 }, [4] = { -0.32, 0.99 } }
            },
            ["Protective Aura"] = { level = 1,
                                    enhancements = { [1] = { -0.75, -0.64 } }
            },
            ["Cursed Ground"] = { level = 1,
                                  enhancements = { [1] = { -0.49, 0.74 }, [2] = { -0.34, 1.05 } }
            },
            ["Void Snare"] = { level = 1,
                               enhancements = { [1] = { -0.41, 0.41 } }
            },
            ["Anticipate Intricacies"] = { level = 1,
                                           enhancements = { [1] = { -0.46, 0.49 }, [2] = { -0.36, 0.8 } }
            },
            ["Peer into Battle"] = { level = 1,
                                     enhancements = { [1] = { -0.41, 0.49 } }
            },
            ["Clairvoyance"] = { level = 1,
                                 enhancements = { [1] = { -0.73, -0.97 } }
            },
            ["Duality Shards"] = { level = "X",
                                   enhancements = { [1] = { -0.33, -0.72 }, [2] = { -0.35, -0.54 }, [3] = { -0.41, 0.5 }, [4] = { -0.32, 0.81 } }
            },
            ["Bad Omen"] = { level = "X",
                             enhancements = { [1] = { 0.01, 0.82 } }
            },
            ["Inspiration from Beyond"] = { level = "X",
                                            enhancements = { [1] = { -0.41, 0.48 }, [2] = { -0.36, 0.75 } }
            },
            ["Revitalizing Fount "] = { level = 2,
                                        enhancements = { [1] = { -0.37, -0.99 }, [2] = { -0.41, -0.59 } }
            },
            ["Gift of the Void"] = { level = 2,
                                     enhancements = { [1] = { -0.41, 0.54 }, [2] = { -0.61, 0.54 } }
            },
            ["Envision the Course"] = { level = 3,
                                        enhancements = { [1] = { 0.2, 0.64 }, [2] = { -0.23, 0.62 }, [3] = { 0.2, 0.83 } }
            },
            ["Call of the Nether"] = { level = 3,
                                       enhancements = { [1] = { -0.22, -0.59 }, [2] = { -0.56, -0.79 }, [3] = { -0.55, -0.4 } }
            },
            ["Cleansing Rite"] = { level = 4,
                                   enhancements = { [1] = { -0.41, -0.98 } }
            },
            ["Preordain the Path"] = { level = 4,
                                       enhancements = { [1] = { -0.41, -0.58 }, [2] = { -0.61, -0.58 } }
            },
            ["Dimensional Divide"] = { level = 5,
                                       enhancements = { [1] = { -0.11, 0.5 } }
            },
            ["Seal Their Fate"] = { level = 5,
                                    enhancements = { [1] = { -0.41, 0.51 }, [2] = { -0.41, 0.75 } }
            },
            ["Careful Attunement"] = { level = 6,
                                       enhancements = { [1] = { -0.41, 0.37 }, [3] = { -0.73, 0.53 } }
            },
            ["Enfeebling Hex"] = { level = 6,
                                   enhancements = { [1] = { -0.5, 0.35 } }
            },
            ["Curative Flux"] = { level = 7,
                                  enhancements = { [1] = { -0.41, -0.84 } }
            },
            ["Ethereal Vortex"] = { level = 7,
                                    enhancements = { [1] = { -0.46, -0.77 } }
            },
            ["Anguish and Salvation"] = { level = 8,
                                          enhancements = { [1] = { -0.49, -0.9 }, [2] = { -0.32, -0.72 }, [3] = { -0.36, 0.43 } }
            },
            ["Deep Contemplation"] = { level = 8,
                                       enhancements = {}
            },
            ["Planar Fissure"] = { level = 9,
                                   enhancements = { [1] = { -0.46, -0.6 }, [2] = { 0.19, 0.63 }, [3] = { -0.24, 0.64 }, [4] = { 0.21, 0.83 } }
            },
            ["Hand of Destiny"] = { level = 9,
                                    enhancements = {}
            }
        }
    },
    --- JOTL
    Demolitionist = {
      isStartingClass = true,
      boxGuid = "aa9c80",
      hp = HpProgression.Medium,
      extra = {
          {
              name = "Rubble",
              type = "Token",
          }
      },
      perks = {
          [1] = { remove = { "(+0)", "(+0)", "(+0)", "(+0)" } },
          [2] = { remove = { "(-1)", "(-1)" } },
          [3] = { remove = { "(-1)", "(-1)" } },
          [4] = { remove = { "(-2)" }, add = { "(+1)" } },
          [5] = { remove = { "(+0)" }, add = { "(+2) (Muddle)" } },
          [6] = { remove = { "(+0)" }, add = { "(+2) (Muddle)" } },
          [7] = { remove = { "(-1)" }, add = { "(+0) (Poison)" } },
          [8] = { add = { "(+2)" } },
          [9] = { add = { "(+2)" } },
          [10] = { remove = { "(+1)" }, add = { "(+2) (Infuse Earth)" } },
          [11] = { remove = { "(+1)" }, add = { "(+2) (Infuse Earth)" } },
          [12] = { remove = { "(+1)" }, add = { "(+2) (Infuse Fire)" } },
          [13] = { remove = { "(+1)" }, add = { "(+2) (Infuse Fire)" } },
          [14] = { add = { "(+0) (All adjacent enemies suffer 1 damage)" } },
          [15] = { add = { "(+0) (All adjacent enemies suffer 1 damage)" } },
      },
      abilities = {
        ["Rubble"] = { level = "X",
          enhancements = {[1]={-0.37, 0.57}}
        },
        ["Level"] = { level = "X",
          enhancements = {[1]={-0.41, -0.74}}
        },
        ["Lobbed Charge"] = { level = "X",
          enhancements = {[1]={-0.41, 0.3}}
        },
        ["Implode"] = { level = 1,
          enhancements = {[1]={-0.37, 0.61}}
        },
        ["One-Two Punch"] = { level = 1,
          enhancements = {[1]={-0.41, -0.91}, [2]={-0.41, -0.67}}
        },
        ["Piston Punch"] = { level = 1,
          enhancements = {[1]={-0.41, -0.76}, [2]={-0.33, -0.6}}
        },
        ["The Big One"] = { level = 1,
          enhancements = {[1]={-0.41, 0.4}}
        },
        ["Crushing Weight"] = { level = 1,
          enhancements = {[1]={-0.41, -0.73}, [2]={-0.36, 0.57}}
        },
        ["Knock Out the Support"] = { level = 1,
          enhancements = {[2]={-0.37, 0.41}, [1]={-0.41, -0.89}}
        },
        ["Windup"] = { level = 1,
          enhancements = {}
        },
        ["Explode"] = { level = 1,
          enhancements = {[1]={-0.37, 0.65}}
        },
        ["Explosive Blitz"] = { level = 1,
          enhancements = {[1]={-0.32, -0.65}, [2]={-0.37, 0.33}}
        },
        ["Robotic Enhancement"] = { level = 2,
          enhancements = {[1]={-0.41, -0.68}, [2]={-0.37, 0.59}}
        },
        ["Crash Protocol"] = { level = 2,
          enhancements = {[1]={-0.37, 0.34}}
        },
        ["Nowhere to Run"] = { level = 3,
          enhancements = {[1]={-0.41, -0.92}, [2]={-0.37, 0.45}}
        },
        ["Fire Bombs"] = { level = 3,
          enhancements = {[1]={-0.32, -0.74}, [2]={-0.33, -0.59}, [3]={-0.36, 0.45}}
        },
        ["Remote Detonation"] = { level = 4,
          enhancements = {[1]={-0.41, -0.67}}
        },
        ["Extra Fuel"] = { level = 4,
          enhancements = {[1]={-0.41, -0.92}, [2]={-0.37, 0.57}}
        },
        ["Mech Suit"] = { level = 5,
          enhancements = {[1]={-0.37, 0.6}}
        },
        ["Dust Cloud"] = { level = 6,
          enhancements = {[1]={-0.37, 0.36}}
        },
        ["Drill Fist"] = { level = 6,
          enhancements = {[1]={-0.37, 0.34}}
        },
        ["Micro Missiles"] = { level = 7,
          enhancements = {[1]={-0.33, -0.58}, [2]={-0.32, -0.44}, [3]={-0.36, 0.45}}
        },
        ["Insult to Injury"] = { level = 7,
          enhancements = {[1]={-0.37, 0.37}}
        },
        ["Gut Punch"] = { level = 8,
          enhancements = {[1]={-0.41, 0.67}}
        },
        ["The Bigger One"] = { level = 8,
          enhancements = {[1]={-0.01, -0.97}}
        },
        ["Collateral Damage"] = { level = 9,
          enhancements = {[1]={-0.41, -0.73}, [2]={-0.37, 0.49}}
        },
        ["Wholesale Destruction"] = { level = 9,
          enhancements = {[1]={-0.41, -0.57}, [2]={-0.41, -0.35}}
        },
      },
    },
    Hatchet = {
      isStartingClass = true,
      boxGuid = "1c647e",
      hp = HpProgression.Medium,
      perks = {
          [1] = { remove = { "(-1)", "(-1)" } },
          [2] = { remove = { "(-1)", "(-1)" } },
          [3] = { remove = { "(+0)" }, add = {"(+2) (Muddle)"} },
          [4] = { remove = { "(+0)" }, add = { "(+1) (Poison)" } },
          [5] = { remove = { "(+0)" }, add = { "(+1) (Wound)" } },
          [6] = { remove = { "(+0)" }, add = { "(+1) (Immobilize)" } },
          [7] = { remove = { "(+0)" }, add = { "(+1) (Push 2)" } },
          [8] = { remove = { "(+0)" }, add = { "(+0) (Stun)" } },
          [9] = { remove = { "(+1)" }, add = { "(+1) (Stun)" } },
          [10] = { add = { "(+2) (Infuse Wind)" } },
          [11] = { add = { "(+2) (Infuse Wind)" } },
          [12] = { add = { "(+2) (Infuse Wind)" } },
          [13] = { remove = { "(+1)" }, add = { "(+3)" } },
          [14] = { remove = { "(+1)" }, add = { "(+3)" } },
          [15] = { remove = { "(+1)" }, add = { "(+3)" } }
      },
      abilities = {
    		["Extra Lift"] = { level = "X",
    		  enhancements = {[1]={-0.41, -0.74}, [2]={-0.32, -0.6}}
    		},
    		["Care Package"] = { level = "X",
    		  enhancements = {[1]={-0.41, -0.91}, [2]={-0.36, -0.52}, [3]={-0.3, 0.82}}
    		},
    		["Fancy Hat"] = { level = "X",
    		  enhancements = {[1]={-0.41, -0.6}}
    		},
    		["Follow Through"] = { level = 1,
    		  enhancements = {[1]={-0.33, -0.65}, [2]={-0.41, 0.42}}
    		},
    		["Center Mass"] = { level = 1,
    		  enhancements = {[1]={-0.41, -0.68}, [3]={-0.37, 0.54}, [2]={-0.32, -0.54}, [4]={-0.41, 0.81}}
    		},
    		["Second Wind"] = { level = 1,
    		  enhancements = {[1]={-0.36, -0.8}}
    		},
    		["Double Throw"] = { level = 1,
    		  enhancements = {[1]={-0.41, -0.89}, [2]={-0.3, -0.59}}
    		},
    		["Stopping Power"] = { level = 1,
    		  enhancements = {[1]={-0.41, -0.74}, [2]={-0.37, 0.33}}
    		},
    		["Power Pitch"] = { level = 1,
    		  enhancements = {[1]={-0.41, 0.61}}
    		},
    		["The Favorite"] = { level = 1,
    		  enhancements = {[1]={-0.37, 0.93}}
    		},
    		["Disorienting Barrage"] = { level = 1,
    		  enhancements = {[1]={-0.33, -0.66}, [2]={-0.33, -0.51}}
    		},
    		["Close Cuts"] = { level = 1,
    		  enhancements = {[1]={-0.41, -0.33}, [2]={-0.41, 0.6}}
    		},
    		["Retrieval"] = { level = 1,
    		  enhancements = {[1]={-0.41, -0.74}}
    		},
    		["Repeat Shot"] = { level = 2,
    		  enhancements = {[1]={-0.41, 0.5}, [2]={-0.32, 0.64}}
    		},
    		["Ricochet"] = { level = 2,
    		  enhancements = {[1]={-0.41, -0.93}, [2]={-0.41, -0.52}}
    		},
    		["Sharpened Blades"] = { level = 3,
    		  enhancements = {[2]={-0.36, 0.65}}
    		},
    		["Fearsome Efficiency"] = { level = 3,
    		  enhancements = {[1]={-0.41, -0.98}, [2]={-0.32, -0.83}}
    		},
    		["Ripped from the Flesh"] = { level = 4,
    		  enhancements = {[1]={-0.36, 0.42}}
    		},
    		["Overwatch"] = { level = 4,
    		  enhancements = {[1]={-0.41, -0.77}, [2]={-0.33, -0.61}}
    		},
    		["The New Favorite"] = { level = 5,
    		  enhancements = {[1]={-0.41, 0.41}}
    		},
    		["Bombardment"] = { level = 6,
    		  enhancements = {[1]={-0.41, 0.46}, [2]={-0.41, 0.91}}
    		},
    		["Quick Turnaround"] = { level = 6,
    		  enhancements = {[1]={-0.33, -0.66}}
    		},
    		["Excessive Force"] = { level = 7,
    		  enhancements = {}
    		},
    		["Brutalize"] = { level = 7,
    		  enhancements = {[1]={-0.41, -0.78}, [2]={-0.41, 0.45}}
    		},
    		["Shrapnel"] = { level = 8,
    		  enhancements = {[1]={-0.33, -0.75}}
    		},
    		["Camaraderie"] = { level = 8,
    		  enhancements = {[1]={-0.36, -0.98}, [2]={-0.36, -0.56}}
    		},
    		["Executioner's Axe"] = { level = 9,
    		  enhancements = {}
    		},
    		["Heart Seeker"] = { level = 9,
    		  enhancements = {[1]={-0.41, -0.81}}
    		},
      }
    },
    ["Red Guard"] = {
      isStartingClass = true,
      boxGuid = "00cfd6",
      hp = HpProgression.High,
      perks = {
          [1] = { remove = { "(+0)", "(+0)", "(+0)", "(+0)" } },
          [2] = { remove = { "(-1)", "(-1)" } },
          [3] = { remove = { "(-2)", "(+1)" } },
          [4] = { remove = { "(-1)" }, add = { "(+1)" } },
          [5] = { remove = { "(-1)" }, add = { "(+1)" } },
          [6] = { remove = { "(+1)" }, add = { "(+2) (Infuse Fire)" } },
          [7] = { remove = { "(+1)" }, add = { "(+2) (Infuse Fire)" } },
          [8] = { remove = { "(+1)" }, add = { "(+2) (Infuse Light)" } },
          [9] = { remove = { "(+1)" }, add = { "(+2) (Infuse Light)" } },
          [10] = { add = { "(+1) (Infuse Fire and Light)" } },
          [11] = { add = { "(+1) (Infuse Fire and Light)" } },
          [12] = { add = { "(+1) (Shield 1 Self)" } },
          [13] = { add = { "(+1) (Shield 1 Self)" } },
          [14] = { remove = { "(+0)" }, add = { "(+1) (Immobilize)" } },
          [15] = { remove = { "(+0)" }, add = { "(+1) (Wound)" } }
      },
      abilities = {
        ["Precision Strike"] = { level = "X",
          enhancements = {[1]={-0.41, -0.94}, [2]={-0.37, 0.52}}
        },
        ["Blade Dance"] = { level = "X",
          enhancements = {[1]={-0.41, -1.02}, [2]={-0.41, -0.39}, [3]={-0.36, 0.34}}
        },
        ["Warrior of the Sun"] = { level = "X",
          enhancements = {[1]={-0.41, -0.91}}
        },
        ["Twirling Stabs"] = { level = 1,
          enhancements = {[1]={-0.41, -0.89}}
        },
        ["Shield Spikes"] = { level = 1,
          enhancements = {[1]={-0.35, 0.53}}
        },
        ["Flaming Sickle"] = { level = 1,
          enhancements = {[1]={-0.41, -0.86}}
        },
        ["Shocking Advance"] = { level = 1,
          enhancements = {[1]={-0.41, -0.9}, [2]={-0.36, 0.6}}
        },
        ["Healing Sands"] = { level = 1,
          enhancements = {[1]={-0.36, -0.81}, [2]={-0.41, 0.43}}
        },
        ["Swift Strength"] = { level = 1,
          enhancements = {[1]={-0.41, -0.81}, [2]={-0.41, 0.82}}
        },
        ["Blinding Sickle"] = { level = 1,
          enhancements = {[1]={-0.41, -0.87}}
        },
        ["Shield of the Desert"] = { level = 1,
          enhancements = {[1]={-0.41, 0.46}}
        },
        ["Desert Night"] = { level = 1,
          enhancements = {[1]={-0.41, -0.87}, [2]={-0.36, 0.52}}
        },
        ["Flame Shroud"] = { level = 1,
          enhancements = {[1]={-0.37, 0.49}}
        },
        ["Harvest Sickle"] = { level = 2,
          enhancements = {[1]={-0.41, -0.82}}
        },
        ["Barbaric Instincts"] = { level = 2,
          enhancements = {[1]={-0.37, -1.01}}
        },
        ["Warmth of the Sun"] = { level = 3,
          enhancements = {[1]={-0.32, 0.7}}
        },
        ["Strangling Chain"] = { level = 3,
          enhancements = {[1]={-0.41, -1.02}, [2]={-0.41, 0.55}}
        },
        ["Radiant Sickle"] = { level = 4,
          enhancements = {[1]={-0.41, -0.92}, [2]={-0.31, 0.98}}
        },
        ["Burn Away the Dark"] = { level = 4,
          enhancements = {[1]={-0.36, 0.39}}
        },
        ["Sand Devil"] = { level = 5,
          enhancements = {}
        },
        ["Fierce Brilliance"] = { level = 6,
          enhancements = {[1]={-0.37, 0.58}}
        },
        ["Flying Sickle"] = { level = 6,
          enhancements = {[1]={-0.41, -0.87}}
        },
        ["Horns of the Beast"] = { level = 7,
          enhancements = {[1]={-0.37, 0.4}, [2]={-0.41, 0.69}}
        },
        ["Vicious Ballet"] = { level = 7,
          enhancements = {[1]={-0.41, -0.94}, [2]={-0.41, 0.97}}
        },
        ["Prismatic Sickle"] = { level = 8,
          enhancements = {[1]={-0.41, -0.85}}
        },
        ["No Fear"] = { level = 8,
          enhancements = {}
        },
        ["Soaring Shield"] = { level = 9,
          enhancements = {[1]={-0.41, 0.76}}
        },
        ["Honorable Fury"] = { level = 9,
          enhancements = {[1]={-0.41, -0.91}}
        },
      },
    },
    Voidwarden = {
        isStartingClass = true,
        boxGuid = "25fbbf",
        hp = HpProgression.Low,
        perks = {
            [1] = { remove = { "(-1)", "(-1)" } },
            [2] = { remove = { "(-2)" } },
            [3] = { remove = { "(+0)" }, add = { "(+1) (Infuse Dark)" } },
            [4] = { remove = { "(+0)" }, add = { "(+1) (Infuse Dark)" } },
            [5] = { remove = { "(+0)" }, add = { "(+1) (Infuse Ice)" } },
            [6] = { remove = { "(+0)" }, add = { "(+1) (Infuse Ice)" } },
            [7] = { remove = { "(-1)" }, add = { "(+0) (Heal 1 Ally)" } },
            [8] = { remove = { "(-1)" }, add = { "(+0) (Heal 1 Ally)" } },
            [9] = { add = { "(+1) (Heal 1 Ally)" } },
            [10] = { add = { "(+1) (Heal 1 Ally)" } },
            [11] = { add = { "(+1) (Heal 1 Ally)" } },
            [12] = { add = { "(+1) (Poison)" } },
            [13] = { add = { "(+3)" } },
            [14] = { add = { "(+1) (Curse)" } },
            [15] = { add = { "(+1) (Curse)" } },
        },
        abilities = {
          ["Resigned Frenzy"] = { level = "X",
            enhancements = {[1]={-0.41, -0.71}}
          },
          ["Sap Warmth"] = { level = "X",
            enhancements = {[1]={-0.41, -1.04}, [2]={-0.41, 0.37}}
          },
          ["Cold Embrace"] = { level = "X",
            enhancements = {[1]={-0.28, -0.64}}
          },
          ["Lure of the Void"] = { level = 1,
            enhancements = {[1]={-0.3, -0.85}}
          },
          ["Turn Out the Lights"] = { level = 1,
            enhancements = {[1]={-0.3, -0.6}, [2]={-0.41, 0.5}}
          },
          ["Suggestion"] = { level = 1,
            enhancements = {[1]={-0.41, -0.89}, [2]={-0.41, -0.62}}
          },
          ["Master Influence"] = { level = 1,
            enhancements = {}
          },
          ["Gift of the Void"] = { level = 1,
            enhancements = {}
          },
          ["Signs of the Void"] = { level = 1,
            enhancements = {[1]={-0.37, -0.84}, [2]={-0.41, -0.44}}
          },
          ["Close to the Abyss"] = { level = 1,
            enhancements = {[1]={-0.31, -0.72}, [2]={-0.31, -0.58}}
          },
          ["Black Boon"] = { level = 1,
            enhancements = {[1]={-0.34, -0.88}, [2]={-0.41, 0.95}}
          },
          ["Freeze the Soul"] = { level = 1,
            enhancements = {[1]={-0.41, -0.73}, [2]={-0.31, 0.55}}
          },
          ["Wicked Scratch"] = { level = 1,
            enhancements = {[1]={-0.41, -0.65}}
          },
          ["Grasp of Doom"] = { level = 1,
            enhancements = {[1]={-0.41, -0.98}, [2]={-0.41, 0.63}}
          },
          ["Give and Take"] = { level = 2,
            enhancements = {[1]={-0.41, 0.32}}
          },
          ["Crushing Cold"] = { level = 3,
            enhancements = {[1]={-0.46, 0.68}}
          },
          ["Taunting Fate"] = { level = 3,
            enhancements = {[1]={-0.34, -0.98}}
          },
          ["Commanding Presence"] = { level = 3,
            enhancements = {[1]={-0.41, 0.32}, [2]={-0.37, 1.21}}
          },
          ["Savage Instinct"] = { level = 4,
            enhancements = {[1]={-0.41, -0.84}}
          },
          ["The Last Journey"] = { level = 4,
            enhancements = {[1]={-0.41, -0.88}}
          },
          ["Stand Fast"] = { level = 5,
            enhancements = {[1]={-0.41, 0.72}}
          },
          ["Withering Conviction"] = { level = 6,
            enhancements = {[1]={-0.41, 0.9}}
          },
          ["Surge of Power"] = { level = 6,
            enhancements = {}
          },
          ["Hateful Blast"] = { level = 7,
            enhancements = {[1]={-0.41, -0.82}, [2]={-0.41, 0.49}}
          },
          ["Spirit Hunger"] = { level = 7,
            enhancements = {[1]={-0.41, -0.84}}
          },
          ["Lull into Oblivion"] = { level = 8,
            enhancements = {[1]={-0.37, 0.82}}
          },
          ["Empowered Link"] = { level = 8,
            enhancements = {[1]={-0.41, 0.43}}
          },
          ["Possessed by Fate"] = { level = 9,
            enhancements = {[1]={-0.41, -0.93}}
          },
          ["Eye of the Void"] = { level = 9,
            enhancements = {[1]={-0.37, 0.35}}
          },
        },
  	},
    --- custom classes starting here
    Witcher = {
        boxGuid = "57b739",
        hp = HpProgression.Medium,
        isCustomClass = true,
        extra = {
            {
                name = "Toxicity Card rules 1/2 and 2/2",
                type = "Rules",
            }
        },
        perks = {
            [1] = { remove = { "(-1)" }, add = { "(+1) (Toxicity -1)" } },
            [2] = { remove = { "(-1)" }, add = { "(+1) (Toxicity -1)" } },
            [3] = { remove = { "(-1)" }, add = { "(+1) (Toxicity -1)" } },
            [4] = { remove = { "(-2)" } },
            [5] = { remove = { "(+0)", "(+0)", "(+0)", "(+0)" }, },
            [6] = { add = { "(+1) (Shield 2 Self)" } },
            [7] = { add = { "(+1) (Disarm)" } },
            [8] = { add = { "(+1) (Disarm)" } },
            [9] = { add = { "(+1) (Strengthen)" } },
            [10] = { remove = { "(+2)" }, add = { "(+4)" } },
            [11] = { add = { "(Add Target) (Rolling)" } },
            [12] = { add = { "(Add Target) (Rolling)" } },
            [13] = { add = { "(Heal +2 Self) (Rolling)" } },
            [14] = { add = { "(Heal +2 Self) (Rolling)" } },
            [15] = { ignore = "I" }
        },
        abilities = {
            ["Sign: Igni"] = { level = 1,
                               enhancements = {}
            },
            ["Sign: Quen"] = { level = 1,
                               enhancements = {}
            },
            ["Sign: Aard"] = { level = 1,
                               enhancements = { [1] = { 0.03, -0.75 }, [2] = { -0.31, 0.46 } }
            },
            ["Dancing Blade"] = { level = 1,
                                  enhancements = {}
            },
            ["Potion: Blizzard"] = { level = 1,
                                     enhancements = { [1] = { -0.3, -0.84 } }
            },
            ["White honey"] = { level = 1,
                                enhancements = {}
            },
            ["Trial of the Grass"] = { level = 1,
                                       enhancements = {}
            },
            ["Whirlwind"] = { level = 1,
                              enhancements = { [1] = { -0.32, -0.68 } }
            },
            ["Potion: Swallows"] = { level = 1,
                                     enhancements = { [1] = { -0.31, 0.4 } }
            },
            ["Potion: Thunderbolt"] = { level = 1,
                                        enhancements = { [1] = { -0.28, -0.77 } }
            },
            ["Toss a Coin"] = { level = 1,
                                enhancements = { [1] = { -0.32, -0.84 } }
            },
            ["Bomb: Devil's Puffball"] = { level = "X",
                                           enhancements = {}
            },
            ["Bomb: Samun"] = { level = "X",
                                enhancements = { [1] = { -0.3, 0.45 } }
            },
            ["Counterattack"] = { level = "X",
                                  enhancements = {}
            },
            ["Potion: Poisoned Blades"] = { level = 2,
                                            enhancements = { [1] = { -0.46, -0.87 }, [2] = { -0.31, 0.4 } }
            },
            ["Sign: Yrden"] = { level = 2,
                                enhancements = {}
            },
            ["Witcher's Contract"] = { level = 3,
                                       enhancements = {}
            },
            ["Potion: Ekimmara"] = { level = 3,
                                     enhancements = { [1] = { -0.06, -0.72 } }
            },
            ["Sign: Enhanced Quen"] = { level = 4,
                                        enhancements = {}
            },
            ["Potion: Petri's philter"] = { level = 4,
                                            enhancements = { [1] = { -0.31, 0.68 } }
            },
            ["Bomb: Northern Wind"] = { level = 5,
                                        enhancements = { [1] = { -0.26, -0.88 } }
            },
            ["Sign: Enhanced Aard"] = { level = 5,
                                        enhancements = { [1] = { 0.16, -0.81 }, [2] = { -0.31, 0.48 } }
            },
            ["Crossbow Shot"] = { level = 6,
                                  enhancements = {}
            },
            ["Sign: Enhanced Igni"] = { level = 6,
                                        enhancements = {}
            },
            ["Silver and Steel"] = { level = 7,
                                     enhancements = {}
            },
            ["Sign: Axii"] = { level = 7,
                               enhancements = {}
            },
            ["Raffard Decoction"] = { level = 8,
                                      enhancements = { [1] = { -0.26, -0.83 } }
            },
            ["Hightened Tolerance"] = { level = 8,
                                        enhancements = {}
            },
            ["Sign: Heliotrope"] = { level = 9,
                                     enhancements = {}
            },
            ["The Wild Hunt"] = { level = 9,
                                  enhancements = {}
            },
        }
    }
}

---@type table<string, gh_Game_Achievement>
Game.Achievements = {
    ["Ancient Technology"] = {
        maxCount = 5
    },
    ["Artifact: Cleansed"] = {
        maxCount = 1
    },
    ["Artifact: Lost"] = {
        maxCount = 1
    },
    ["Artifact: Recovered"] = {
        maxCount = 1
    },
    ["City Rule: Demonic"] = {
        maxCount = 1
    },
    ["City Rule: Economic"] = {
        maxCount = 1
    },
    ["City Rule: Militaristic"] = {
        maxCount = 1
    },
    ["End of Corruption"] = {
        maxCount = 3
    },
    ["End of Gloom"] = {
        maxCount = 1
    },
    ["End of the Invasion"] = {
        maxCount = 1
    },
    ["The Annihilation of the Order"] = {
        maxCount = 1
    },
    ["The Dead Invade"] = {
        maxCount = 1
    },
    ["The Rift Neutralized"] = {
        maxCount = 1
    },
    ["The Drake Aided"] = {
        maxCount = 1
    },
    ["The Drake Slain"] = {
        maxCount = 1
    },
    ["The Edge of Darkness"] = {
        maxCount = 1
    },
    ["The Merchant Flees"] = {
        maxCount = 1
    },
    ["The Power of Enhancement"] = {
        maxCount = 1
    },
    ["The Voice Freed"] = {
        maxCount = 1
    },
    ["The Voice Silenced"] = {
        maxCount = 1
    },
    ["Water-Breathing"] = {
        maxCount = 1
    },
    ["Through the Portal"] = {
        maxCount = 1
    },
    ["Severed Ties"] = {
        maxCount = 1
    },
    ["Knowledge is Power"] = {
        maxCount = 4
    },
    ["Peril Adverted"] = {
        maxCount = 4
    },
    ["Pieces of an Artifact"] = {
        maxCount = 3
    },
    ["Mechanical Splendor"] = {
        maxCount = 1
    },
}

---Information about Personal quests.
---@type gh_Game_Quests
Game.Quests = {
    ["A Helping Hand"] = {
        index = 0,
        number = 532
    },
    ["A Study of Anatomy"] = {
        index = 1,
        number = 514
    },
    ["Aberrant Slayer"] = {
        index = 2,
        number = 523
    },
    ["Augmented Abilities"] = {
        index = 3,
        number = 530
    },
    ["Battle Legend"] = {
        index = 4,
        number = 519
    },
    ["Elemental Samples"] = {
        index = 5,
        number = 531
    },
    ["Eternal Wanderer"] = {
        index = 6,
        number = 518
    },
    ["Fearless Stand"] = {
        index = 7,
        number = 524
    },
    ["Finding the Cure"] = {
        index = 8,
        number = 513
    },
    ["Goliath Toppler"] = {
        index = 9,
        number = 528
    },
    ["Greed is Good"] = {
        index = 10,
        number = 512
    },
    ["Implement of Light"] = {
        index = 11,
        number = 520
    },
    ["Law Bringer"] = {
        index = 12,
        number = 515
    },
    ["Merchant Class"] = {
        index = 13,
        number = 511
    },
    ["Piety in All Things"] = {
        index = 14,
        number = 525
    },
    ["Pounds of Flesh"] = {
        index = 15,
        number = 516
    },
    ["Seeker of Xorn"] = {
        index = 16,
        number = 510
    },
    ["Take Back the Trees"] = {
        index = 17,
        number = 521
    },
    ["The Fall of Man"] = {
        index = 18,
        number = 529
    },
    ["The Perfect Poison"] = {
        index = 19,
        number = 533
    },
    ["The Thin Places"] = {
        index = 20,
        number = 522
    },
    ["Trophy Hunt"] = {
        index = 21,
        number = 517
    },
    ["Vengeance"] = {
        index = 22,
        number = 526
    },
    ["Zealot of the Blood God"] = {
        index = 23,
        number = 527
    },
}

--- List of treasure numbers per scenario.
---@type table<number, number[]>
Game.Scenario = {
    [1] = { 7 },
    [2] = { 67 },
    [3] = { 65 },
    [4] = { 38, 46 },
    [5] = { 4, 28 },
    [6] = { 50 },
    [7] = { },
    [8] = { 51 },
    [9] = { },
    [10] = { 11 },
    [11] = { 5 },
    [12] = { 34 },
    [13] = { 10 },
    [14] = { 26 },
    [15] = {},
    [16] = { 1 },
    [17] = { 71 },
    [18] = { 63 },
    [19] = { 17 },
    [20] = { 60 },
    [21] = { 15 },
    [22] = { 21 },
    [23] = { 39, 72 },
    [24] = { 70 },
    [25] = { 58 },
    [26] = { 66 },
    [27] = {},
    [28] = { 32 },
    [29] = { 41 },
    [30] = {},
    [31] = { 69 },
    [32] = {},
    [33] = {},
    [34] = { 23 },
    [35] = { 61 },
    [36] = { 2 },
    [37] = { 49 },
    [38] = { 29 },
    [39] = { 73 },
    [40] = { 47 },
    [41] = { 24 },
    [42] = { 30, 55 },
    [43] = { 35 },
    [44] = {},
    [45] = { 74 },
    [46] = { 48 },
    [47] = { 18, 57 },
    [48] = { 64 },
    [49] = { 44 },
    [50] = {},
    [51] = { 56 },
    [52] = {},
    [53] = { 31 },
    [54] = { 25 },
    [55] = {},
    [56] = { 45 },
    [57] = { 3, 22 },
    [58] = {},
    [59] = {},
    [60] = {},
    [61] = {},
    [62] = { 59 },
    [63] = { 12 },
    [64] = { 9 },
    [65] = {},
    [66] = { 16, 36 },
    [67] = { 14 },
    [68] = { 33 },
    [69] = {},
    [70] = { 6 },
    [71] = {},
    [72] = {},
    [73] = {},
    [74] = { 20 },
    [75] = { 53 },
    [76] = { 75 },
    [77] = {},
    [78] = {},
    [79] = { 52 },
    [80] = {},
    [81] = { 68 },
    [82] = { 62 },
    [83] = {},
    [84] = { 42 },
    [85] = {},
    [86] = {},
    [87] = { 40 },
    [88] = { 8, 37 },
    [89] = { 13, 27, 43 },
    [90] = { 19 },
    [91] = {},
    [92] = {},
    [93] = { 54 },
    [94] = {},
    [95] = {},
    [96] = { 91 },
    [97] = { 96 },
    [98] = { 79 },
    [99] = { 95 },
    [100] = { 76, 85 },
    [101] = { 93 },
    [102] = { 77, 86 },
    [103] = { 81 },
    [104] = { 87 },
    [105] = { 83, 88 },
    [106] = {},
    [107] = { 78, 90 },
    [108] = {},
    [109] = { 80, 94 },
    [110] = { 84 },
    [111] = { 82 },
    [112] = {},
    [113] = {},
    [114] = {},
    [115] = { 96 },
}

return Game
