Rotation = {}
Rotation.NORTH = vector(0, 180, 0)
Rotation.NORTH_FLIPPED = vector(0, 180, 180)
Rotation.EAST = vector(0, 270, 0)
Rotation.EAST_FLIPPED = vector(0, 270, 180)
Rotation.SOUTH = vector(0, 0, 0)
Rotation.SOUTH_FLIPPED = vector(0, 0, 180)
Rotation.WEST = vector(0, 90, 0)
Rotation.WEST_FLIPPED = vector(0, 90, 180)

Direction = {}
Direction.UP = {0, 1, 0}
Direction.DOWN = {0, -1, 0}

Tag = {}
Tag.FIGURINE = "Figurine"
Tag.CARD = "Card"
