Enhancement = {}

Enhancement.DECALS = {
  ["Air"] = "http://cloud-3.steamusercontent.com/ugc/938309024726768884/CC8308C7D7DD6185F3EFA99F452C83101E1E95E3/",
  ["Earth"] = "http://cloud-3.steamusercontent.com/ugc/938309024726773039/E83D1E9F06938B3B5355F0A6A49D98B78B1F2594/",
  ["Fire"] = "http://cloud-3.steamusercontent.com/ugc/938309024726770166/CD369CF7C22FAD932A71C65BA811AE137234270D/",
  ["Frost"] = "http://cloud-3.steamusercontent.com/ugc/938309024726771564/3C69B7D1E66E8FC022B2BD77CC427E8AEC5D9331/",
  ["Ice"] = "http://cloud-3.steamusercontent.com/ugc/938309024726771564/3C69B7D1E66E8FC022B2BD77CC427E8AEC5D9331/", -- Some as Frost
  ["Dark"] = "http://cloud-3.steamusercontent.com/ugc/938309024726982499/9C14793623433565A9D6E5B3C608C1F6FBB84C76/",
  ["Light"] = "http://cloud-3.steamusercontent.com/ugc/938309024726774294/5BBAC718ED55E90563D2B24848DE3ACAEBD76FE9/",
  ["Any Element"] = "http://cloud-3.steamusercontent.com/ugc/938309024726984504/2F962A64E2A9888C90856D9C150EF81089745137/",
  ["Curse"] = "http://cloud-3.steamusercontent.com/ugc/938309024726987796/ABB2E197E22015077D39A378AA9A9E7A317C69FE/",
  ["Bless"] = "http://cloud-3.steamusercontent.com/ugc/938309024726986639/FDF514FDA20826ACA054BE5CBA579AE6FB25A263/",
  ["Disarm"] = "http://cloud-3.steamusercontent.com/ugc/938309024726989091/DB993A58BC37C60B64A2F2CCDAED888F6176BC43/",
  ["Immobilize"] = "http://cloud-3.steamusercontent.com/ugc/938309024726990928/14B27BE1DC8F226D05FDB7D7D5D420FFCA6919B0/",
  ["Muddle"] = "http://cloud-3.steamusercontent.com/ugc/938309024726993395/820BE84906894B87F0C0DAC77C3BFBCD9B1AD504/",
  ["Poison"] = "http://cloud-3.steamusercontent.com/ugc/938309024726994202/6EAECD4A8A6A56F42834D486A21219002B883C53/",
  ["Regenerate"] = "http://cloud-3.steamusercontent.com/ugc/791986676667649885/92F7F934D298524F6F72997095DDBA073D9A15BF/",
  ["Strengthen"] = "http://cloud-3.steamusercontent.com/ugc/938309024726995467/72FC8E8918F788646DBD0C571FDAB214D7A36445/",
  ["Stun"] = "http://cloud-3.steamusercontent.com/ugc/83721958671678940/616CC0951CB17024448D3CBC7E5CA9D3A05D7555/",
  ["Wound"] = "http://cloud-3.steamusercontent.com/ugc/938309024726992099/9B90EEDC5B68B4FFD04C0037008F9C96BA603C24/",
  ["Plus 1"] = "http://cloud-3.steamusercontent.com/ugc/938309024726761532/C3BB327E15466B74ED256A0BD7B66C20A8825861/",
  ["Area"] = "http://cloud-3.steamusercontent.com/ugc/938309024726997997/041C0C738331AA8B4D8281BE8E9BE2C2963D823D/",
  ["Jump"] = "http://cloud-3.steamusercontent.com/ugc/938309024726767406/7C34D7EA30D5E6FF90BBA88A767ACB98467FC557/"
}

Enhancement.NUMBERS = {
  "http://cloud-3.steamusercontent.com/ugc/929311677225889607/DFA4EF43DC2D1A8B6F1C7F22E7C31718E35CCB31/",
  "http://cloud-3.steamusercontent.com/ugc/929311677225890374/9B9B38BE2BB6A23EC21C977911FEC8915C74FF19/",
  "http://cloud-3.steamusercontent.com/ugc/929311677225891903/93FF8C7F051FDD06DAEBD17F2BBD917960CB1779/",
  "http://cloud-3.steamusercontent.com/ugc/929311677225892191/F2D0FC8179C04D3E4BFD2A546FAD7BC76D813091/",
  "http://cloud-3.steamusercontent.com/ugc/929311677225892469/3DC5E471FC5F2CB1D6DBFC91DF5ADB2751A52E12/",
  "http://cloud-3.steamusercontent.com/ugc/929311677225892918/3720A0E91CA48BB3972BBE924B26A34FFA34F57F/"
}

Enhancement.Y_COORDINATE = 0.36
Enhancement.ROTATION =  {90, 180, 0}
Enhancement.SCALE = {0.16, 0.16, 3.07}


function Enhancement.loadAll(saveFile)
  if not saveFile.enhancements then
    return
  end
  print("Loading Enhancements")

  for className, abilities in pairs(saveFile.enhancements) do
    Enhancement.loadForClass(className, abilities)
  end
end


function Enhancement.loadForClass(className, abilities)
  local playerZone = Character.findZoneForClass(className)
  for ability, enhancements in pairs(abilities) do
    local enhancementInfo = Game.CLASSES[className].abilities[ability].enhancements

    local abilityCard = utils.find_object_in_zone(playerZone, {name=ability})
    if abilityCard then
      Enhancement.loadForCard(abilityCard, enhancements, enhancementInfo)
    else
      local abilityDeck = Component.abilityDeck(playerZone)
      local abilityCard = utils.find_object_info_in_stack(abilityDeck, {name=ability})
      abilityDeck.takeObject({
        guid = abilityCard.guid,
        position = Character.get_safe_position(),
        rotation = abilityDeck.getRotation(),
        smooth = false,
        callback_function = function(obj)
                              Enhancement.loadForCard(obj, enhancements, enhancementInfo)
                              abilityDeck.putObject(obj)
                            end
      })
    end
  end
end


function Enhancement.loadForCard(abilityCard, enhancements, enhancementInfo)
  for i, enhancement in pairs(enhancements) do
    local position = enhancementInfo[tonumber(i)]
    abilityCard.addDecal({
      name = "Enhancement " .. enhancement,
      url = Enhancement.DECALS[enhancement],
      position = {position[1], Enhancement.Y_COORDINATE, position[2]},
      rotation = Enhancement.ROTATION,
      scale = Enhancement.SCALE
    })
  end
end
