-- Contains information about different parts of the Gloomhaven mod and Gloomhaven components (e.g.
-- all classes and their perks).
info = {}

-- Mapping from a player's scripting zone GUID to PlayerColor
info.PLAYERS = {
  [guids.ZONES[1]] = "Red",
  [guids.ZONES[2]] = "White",
  [guids.ZONES[3]] = "Blue",
  [guids.ZONES[4]] = "Green"
}

info.HP = {
  LOW = {6, 7, 8, 9, 10, 11, 12, 13, 14},
  MEDIUM =  {8, 9, 11, 12, 14, 15, 17, 18, 20},
  HIGH = {10, 12, 14, 16, 18, 20, 22, 24, 26}
}

info.XPLevel = {0, 45, 95, 150, 210, 275, 345, 420, 500}

-- Information about all character classes. Contains their name, components GUIDs, perks and HP.
info.CLASSES = {
  Brute = {
    isStartingClass = true,
    box_guid = "697f18",
    hp = info.HP.HIGH,
    perks = {
      [1] = { remove = {"(-1)", "(-1)"} },
      [2] = { add = {"(+1)"}, remove = {"(-1)"} },
      [3] = { add = {"(+1)", "(+1)"} },
      [4] = { add = {"(+1)", "(+1)"} },
      [5] = { add = {"(+3)"} },
      [6] = { add = {"(Push 1) (Rolling)", "(Push 1) (Rolling)", "(Push 1) (Rolling)"} },
      [7] = { add = {"(Push 1) (Rolling)", "(Push 1) (Rolling)", "(Push 1) (Rolling)"} },
      [8] = { add = {"(Pierce 3) (Rolling)", "(Pierce 3) (Rolling)"} },
      [9] = { add = {"(Stun) (Rolling)"} },
      [10] = { add = {"(Stun) (Rolling)"} },
      [11] = { add = {"(Disarm) (Rolling)", "(Muddle) (Rolling)"} },
      [12] = { add = {"(Add Target) (Rolling)"} },
      [13] = { add = {"(Add Target) (Rolling)"} },
      [14] = { add = {"(+1) (Shield 1 Self)"} },
      [15] = { add = {"(+1)"}, ignore = "I"}
    },
    abilities = {
      ["Eye for an Eye"] = {level = 1},
      ["Trample"] = {level = 1},
      ["Grab and Go"] = {level = 1},
      ["Overwhelming Assault"] = {level = 1},
      ["Provoking Roar"] = {level = 1},
      ["Shield Bash"] = {level = 1},
      ["Sweeping Blow"] = {level = 1},
      ["Warding Strength"] = {level = 1},
      ["Leaping Cleave"] = {level = 1},
      ["Spare Dagger"] = {level = 1},
      ["Wall of Doom"] = {level = "X"},
      ["Skewer"] = {level = "X"},
      ["Balanced Measure"] = {level = "X"}
    }
  },
  Scoundrel = {
    isStartingClass = true,
    box_guid = "66309d",
    hp = info.HP.MEDIUM,
    perks = {
      [1] = { remove = {"(-1)", "(-1)"} },
      [2] = { remove = {"(-1)", "(-1)"} },
      [3] = { remove = {"(+0)", "(+0)", "(+0)", "(+0)"} },
      [4] = { remove = {"(-2)"}, add = {"(+0)"} },
      [5] = { remove = {"(-1)"}, add = {"(+1)"} },
      [6] = { remove = {"(+0)"}, add = {"(+2)"} },
      [7] = { remove = {"(+0)"}, add = {"(+2)"} },
      [8] = { add = {"(+1) (Rolling)", "(+1) (Rolling)"} },
      [9] = { add = {"(+1) (Rolling)", "(+1) (Rolling)"} },
      [10] = { add = {"(Pierce 3) (Rolling)", "(Pierce 3) (Rolling)"} },
      [11] = { add = {"(Poison) (Rolling)", "(Poison) (Rolling)"} },
      [12] = { add = {"(Poison) (Rolling)", "(Poison) (Rolling)"} },
      [13] = { add = {"(Muddle) (Rolling)", "(Muddle) (Rolling)"} },
      [14] = { add = {"(Invisible) (Rolling)"} },
      [15] = { ignore = "S" }
    },
    abilities = {
      ["Flanking Strike"] = {level = 1},
      ["Special Mixture"] = {level = 1},
      ["Throwing Knives"] = {level = 1},
      ["Thief's Knack"] = {level = 1},
      ["Quick Hands"] = {level = 1},
      ["Backstab"] = {level = 1},
      ["Smoke Bomb"] = {level = 1},
      ["Single Out"] = {level = 1},
      ["Venom Shiv"] = {level = 1},
      ["Sinister Opportunity"] = {level = "X"},
      ["Trickster's Reversal"] = {level = "X"},
      ["Swift Bow"] = {level = "X"}
    }
  },
  Spellweaver = {
    isStartingClass = true,
    box_guid = "0507cf",
    hp = info.HP.LOW,
    perks = {
      [1] = { remove = {"(+0)", "(+0)", "(+0)", "(+0)"} },
      [2] = { remove = {"(-1)"}, add = {"(+1)"} },
      [3] = { remove = {"(-1)"}, add = {"(+1)"} },
      [4] = { add = {"(+1)", "(+1)"} },
      [5] = { add = {"(+1)", "(+1)"} },
      [6] = { add = {"(+0) (Stun)"} },
      [7] = { add = {"(+1) (Wound)"} },
      [8] = { add = {"(+1) (Immobilize)"} },
      [9] = { add = {"(+1) (Curse)"} },
      [10] = { add = {"(+2) (Fire)"} },
      [11] = { add = {"(+2) (Fire)"} },
      [12] = { add = {"(+2) (Ice)"} },
      [13] = { add = {"(+2) (Ice)"} },
      [14] = { add = {"(Earth) (Rolling)", "(Air) (Rolling)"} },
      [15] = { add = {"(Dark) (Rolling)", "(Light) (Rolling)"} },
    },
    abilities = {
      ["Flame Strike"] = {level = 1},
      ["Frost Armor"] = {level = 1},
      ["Fire Orbs"] = {level = 1},
      ["Impaling Eruption"] = {level = 1},
      ["Mana Bolt"] = {level = 1},
      ["Reviving Ether"] = {level = 1},
      ["Freezing Nova"] = {level = 1},
      ["Ride the Wind"] = {level = 1},
      ["Crackling Air"] = {level = "X"},
      ["Aid from the Ether"] = {level = "X"},
      ["Hardened Spikes"] = {level = "X"}
    }
  },
  Mindthief = {
    isStartingClass = true,
    box_guid = "8c1ca4",
    hp = info.HP.LOW,
    perks = {
      [1] = { remove = {"(-1)", "(-1)"} },
      [2] = { remove = {"(-1)", "(-1)"} },
      [3] = { remove = {"(+0)", "(+0)", "(+0)", "(+0)"} },
      [4] = { remove = {"(+1)", "(+1)"}, add = {"(+2)", "(+2)"} },
      [5] = { remove = {"(-2)"}, add = {"(+0)"} },
      [6] = { add = {"(+2) (Ice)"} },
      [7] = { add = {"(+2) (Ice)"} },
      [8] = { add = {"(+1) (Rolling)", "(+1) (Rolling)"}},
      [9] = { add = {"(+1) (Rolling)", "(+1) (Rolling)"} },
      [10] = { add = {"(Pull 1) (Rolling)", "(Pull 1) (Rolling)", "(Pull 1) (Rolling)"} },
      [11] = { add = {"(Muddle) (Rolling)", "(Muddle) (Rolling)", "(Muddle) (Rolling)"} },
      [12] = { add = {"(Immobilize) (Rolling)", "(Immobilize) (Rolling)"} },
      [13] = { add = {"(Stun) (Rolling)"} },
      [14] = { add = {"(Disarm) (Rolling)", "(Muddle) (Rolling)"} },
      [15] = { ignore = "S"}
    },
    abilities = {
      ["Empathetic Assault"] = {level = 1},
      ["Perverse Edge"] = {level = 1},
      ["Gnawing Horde"] = {level = 1},
      ["Into the Night"] = {level = 1},
      ["Feedback Loop"] = {level = 1},
      ["Fearsome Blade"] = {level = 1},
      ["The Mind's Weakness"] = {level = 1},
      ["Parasitic Influence"] = {level = 1},
      ["Scurry"] = {level = 1},
      ["Submissive Affliction"] = {level = 1},
      ["Possession"] = {level = "X"},
      ["Withering Claw"] = {level = "X"},
      ["Frigid Apparition"] = {level = "X"}
    }
  },
  Cragheart = {
    isStartingClass = true,
    box_guid = "ec1d2a",
    hp = info.HP.HIGH,
    perk = {
      [1] = { remove = {"(+0)", "(+0)", "(+0)", "(+0)"} },
      [2] = { remove = {"(-1)"}, add = {"(+1)"}},
      [3] = { remove = {"(-1)"}, add = {"(+1)"} },
      [4] = { remove = {"(-1)"}, add = {"(+1)"} },
      [5] = { add = {"(-2)", "(+2)", "(+2)"} },
      [6] = { add = {"(+1) (Immobilize)"} },
      [7] = { add = {"(+1) (Immobilize)"} },
      [8] = { add = {"(+2) (Muddle)"} },
      [9] = { add = {"(+2) (Muddle)"} },
      [10] = { add = {"(Push 2) (Rolling)", "(Push 2) (Rolling)"} },
      [11] = { add = {"(Earth) (Rolling)", "(Earth) (Rolling)"} },
      [12] = { add = {"(Earth) (Rolling)", "(Earth) (Rolling)"} },
      [13] = { add = {"(Air) (Rolling)", "(Air) (Rolling)"} },
      [14] = { ignore = "S" },
      [15] = { ignore = "I" }
    },
    abilities = {
      ["Dirt Tornado"] = {level = 1},
      ["Crater"] = {level = 1},
      ["Rock Tunnel"] = {level = 1},
      ["Rumbling Advance"] = {level = 1},
      ["Unstable Upheaval"] = {level = 1},
      ["Backup Ammunition"] = {level = 1},
      ["Earthen Clod"] = {level = 1},
      ["Avalanche"] = {level = 1},
      ["Massive Boulder"] = {level = 1},
      ["Opposing Strike"] = {level = 1},
      ["Crushing Grasp"] = {level = 1},
      ["Heaving Swing"] = {level = "X"},
      ["Forceful Storm"] = {level = "X"},
      ["Nature's Lift"] = {level = "X"}
    }
  },
  Tinkerer = {
    isStartingClass = true,
    box_guid = "fdef02",
    hp = info.HP.MEDIUM,
    perks = {
      [1] = { remove = {"(-1)", "(-1)"} },
      [2] = { remove = {"(-1)", "(-1)"} },
      [3] = { remove = {"(-2)"}, add = {"(+0)"} },
      [4] = { add = {"(+1)", "(+1)"} },
      [5] = { add = {"(+3)"} },
      [6] = { add = {"(Fire) (Rolling)", "(Fire) (Rolling)"} },
      [7] = { add = {"(Muddle) (Rolling)", "(Muddle) (Rolling)", "(Muddle) (Rolling)"} },
      [8] = { add = {"(+1) (Wound)"} },
      [9] = { add = {"(+1) (Wound)"} },
      [10] = { add = {"(+1) (Immobilize)"} },
      [11] = { add = {"(+1) (Immobilize)"} },
      [12] = { add = {"(+1) (Heal 2 Self)"} },
      [13] = { add = {"(+1) (Heal 2 Self)"} },
      [14] = { add = {"(+0) (Add Target)"} },
      [15] = { ignore = "S" }
    },
    abilities = {
      ["Proximity Mine"] = {level = 1},
      ["Hook Gun"] = {level = 1},
      ["Enhancement Field"] = {level = 1},
      ["Toxic Bolt"] = {level = 1},
      ["Restorative Mist"] = {level = 1},
      ["Energizing Tonic"] = {level = 1},
      ["Stun Shot"] = {level = 1},
      ["Harmless Contraption"] = {level = 1},
      ["Flamethrower"] = {level = 1},
      ["Reinvigorating Elixir"] = {level = 1},
      ["Net Shooter"] = {level = 1},
      ["Ink Bomb"] = {level = 1},
      ["Reviving Shock"] = {level = "X"},
      ["Potent Potables"] = {level = "X"},
      ["Volatile Concoction"] = {level = "X"}
    }
  },
  Berserker = {
    box_guid = "7ff6c4",
    hp = info.HP.HIGH,
    perks = {
      [1] = { remove = {"(-1)", "(-1)"} },
      [2] = { remove = {"(+0)", "(+0)", "(+0)", "(+0)"} },
      [3] = { remove = {"(-1)"}, add = {"(+1)"}},
      [4] = { remove = {"(-1)"}, add = {"(+1)"} },
      [5] = { remove = {"(+0)"}, add = {"(+2) (Rolling)"} },
      [6] = { remove = {"(+0)"}, add = {"(+2) (Rolling)"} },
      [7] = { add = {"(Wound) (Rolling)", "(Wound) (Rolling)"} },
      [8] = { add = {"(Wound) (Rolling)", "(Wound) (Rolling)"} },
      [9] = { add = {"(Stun) (Rolling)"} },
      [10] = { add = {"(Stun) (Rolling)"} },
      [11] = { add = {"(+1) (Disarm) (Rolling)"} },
      [12] = { add = {"(Heal 1 Self)", "(Heal 1 Self)"} },
      [13] = { add = {"(+2) (Fire)"} },
      [14] = { add = {"(+2) (Fire)"} },
      [15] = { ignore = "I" }
    },
    abilities = {
      ["Dazing Wound"] = {level = 1},
      ["Bounce Back"] = {level = 1},
      ["Growing Rage"] = {level = 1},
      ["Cauterize"] = {level = 1},
      ["Resolute Stand"] = {level = 1},
      ["Furious Aid"] = {level = 1},
      ["From the Brink"] = {level = 1},
      ["Strength in Agony"] = {level = 1},
      ["Defiance of Death"] = {level = 1},
      ["Blood Pact"] = {level = 1},
      ["Numb the Pain"] = {level = "X"},
      ["Unbridled Power"] = {level = "X"},
      ["Glass Hammer"] = {level = "X"}
    }
  },
  Elementalist = {
    box_guid = "21d7e7",
    info.HP.LOW,
    perks = {
      [1] = { remove = {"(-1)", "(-1)"} },
      [2] = { remove = {"(-1)", "(-1)"} },
      [3] = { remove = {"(-1)"}, add = {"(+1)"} },
      [4] = { remove = {"(+0)"}, add = {"(+2)"} },
      [5] = { remove = {"(+0)"}, add = {"(+2)"} },
      [6] = { add = {"(Fire)", "(Fire)", "(Fire)"} },
      [7] = { add = {"(Ice)", "(Ice)", "(Ice)"} },
      [8] = { add = {"(Air)", "(Air)", "(Air)"} },
      [9] = { add = {"(Earth)", "(Earth)", "(Earth)"} },
      [10] = { remove = {"(+0)", "(+0)"}, add = {"(Fire)", "(Earth)"}},
      [11] = { remove = {"(+0)", "(+0)"}, add = {"(Ice)", "(Air)"}},
      [12] = { add = {"(+1) (Push 1)", "(+1) (Push 1)"} },
      [13] = { add = {"(+1) (Wound)"} },
      [14] = { add = {"(Stun)"} },
      [15] = { add = {"(Add Target)"} }
    },
    abilities = {
      ["Pure Augmentation"] = {level = 1},
      ["Raw Enhancement"] = {level = 1},
      ["Formless Power"] = {level = 1},
      ["Tremulant Cyclone"] = {level = 1},
      ["Shaping the Ether"] = {level = 1},
      ["Land Eruption"] = {level = 1},
      ["Stoking Hail"] = {level = 1},
      ["Infernal Vortex"] = {level = 1},
      ["Ice Spikes"] = {level = 1},
      ["Frigid Torrent"] = {level = 1},
      ["Encompassing Shadow"] = {level = "X"},
      ["Brilliant Flash"] = {level = "X"},
      ["Malleable Evocation"] = {level = "X"}
    }
  },
  Quartermaster = {
    box_guid = "d221fc",
    hp = info.HP.HIGH,
    perks = {
      [1] = { remove = {"(-1)", "(-1)"} },
      [2] = { remove = {"(-1)", "(-1)"} },
      [3] = { remove = {"(+0)", "(+0)", "(+0)", "(+0)"} },
      [4] = { remove = {"(+0)"}, add = {"(+2)"} },
      [5] = { remove = {"(+0)"}, add = {"(+2)"} },
      [6] = { add = {"(+1) (Rolling)", "(+1) (Rolling)"} },
      [7] = { add = {"(+1) (Rolling)", "(+1) (Rolling)"} },
      [8] = { add = {"(Muddle) (Rolling)", "(Muddle) (Rolling)", "(Muddle) (Rolling)"} },
      [9] = { add = {"(Pierce 3) (Rolling)", "(Pierce 3) (Rolling)"} },
      [10] = { add = {"(Stun) (Rolling)"} },
      [11] = { add = {"(Add Target) (Rolling)"} },
      [12] = { add = {"(Refresh)"}},
      [13] = { add = {"(Refresh"} },
      [14] = { add = {"(Refresh)"} },
      [15] = { ignore= "I", add = {"(+1)", "(+1)"} }
    },
    abilities = {
      ["Impaling Spear"] = {level = 1},
      ["Cleaving Axe"] = {level = 1},
      ["Hastened Step"] = {level = 1},
      ["Iron Bulwark"] = {level = 1},
      ["Crippling Bow"] = {level = 1},
      ["Oversized Pack"] = {level = 1},
      ["Sharpening Kit"] = {level = 1},
      ["Restock"] = {level = 1},
      ["Proficiency"] = {level = 1},
      ["Crushing Hammer"] = {level = "X"},
      ["Scroll of Recall"] = {level = "X"},
      ["Reserved Energy"] = {level = "X"}
    }
  },
  ["Beast Tyrant"] = {
    box_guid = "89bec7",
    hp = info.HP.LOW,
    extra_figure = {
      name = "Bear Companion",
      hp = info.HP.HIGH
    },
    perks = {
      [1] = { remove = {"(-1)", "(-1)"} },
      [2] = { remove = {"(-1)"}, add = {"(+1)"} },
      [3] = { remove = {"(-1)"}, add = {"(+1)"} },
      [4] = { remove = {"(-1)"}, add = {"(+1)"} },
      [5] = { remove = {"(+0)"}, add = {"(+2)"} },
      [6] = { remove = {"(+0)"}, add = {"(+2)"} },
      [7] = { add = {"(+1) (Wound)"} },
      [8] = { add = {"(+1) (Wound)"} },
      [9] = { add = {"(+1) (Immobilize)"} },
      [10] = { add = {"(+1) (Immobilize)"} },
      [11] = { add = {"(Heal +1 Self) (Rolling)", "(Heal +1 Self) (Rolling)"} },
      [12] = { add = {"(Heal +1 Self) (Rolling)", "(Heal +1 Self) (Rolling)"} },
      [13] = { add = {"(Heal +1 Self) (Rolling)", "(Heal +1 Self) (Rolling)"} },
      [14] = { add = {"(Earth) (Rolling)", "(Earth) (Rolling)"} },
      [15] = { ignore = "S" }
    },
    abilities = {
      ["Venemous Ally"] = {level = 1},
      ["Spirit Swap"] = {level = 1},
      ["Disappearing Wounds"] = {level = 1},
      ["Maul"] = {level = 1},
      ["Patch Fur"] = {level = 1},
      ["Forceful Swipe"] = {level = 1},
      ["Howling Bolts"] = {level = 1},
      ["Disorienting Roar"] = {level = 1},
      ["Relentless Ally"] = {level = 1},
      ["Concentrated Rage"] = {level = 1},
      ["Borrowed Essence"] = {level = "X"},
      ["Focussed Aggresion"] = {level = "X"},
      ["Soaring Ally"] = {level = "X"}
    }
  },
  Soothsinger = {
    box_guid = "732351",
    hp = info.HP.LOW,
    perks = {
      [1] = { remove = {"(-1)", "(-1)"} },
      [2] = { remove = {"(-1)", "(-1)"} },
      [3] = { remove = {"(-2)"} },
      [4] = { remove = {"(+1)", "(+1)"}, add = {"(+4)"} },
      [5] = { remove = {"(+1)", "(+1)"}, add = {"(+4)"} },
      [6] = { remove = {"(+0)"}, add = {"(+1) (Immobilize)"} },
      [7] = { remove = {"(+0)"}, add = {"(+1) (Disarm)"} },
      [8] = { remove = {"(+0)"}, add = {"(+2) (Wound)"} },
      [9] = { remove = {"(+0)"}, add = {"(+2) (Poison)"} },
      [10] = { remove = {"(+0)"}, add = {"(+2) (Curse)"} },
      [11] = { remove = {"(+0)"}, add = {"(+3) (Muddle)"} },
      [12] = { remove = {"(-1)"}, add = {"(+0) (Stun)"} },
      [13] = { add = {"(+1) (Rolling)", "(+1) (Rolling)", "(+1) (Rolling)"} },
      [14] = { add = {"(Curse) (Rolling)", "(Curse) (Rolling)"} },
      [15] = { add = {"(Curse) (Rolling)", "(Curse) (Rolling)"} }
    },
    abilities = {
      ["Throw Voice"] = {level = 1},
      ["Warding Dagger"] = {level = 1},
      ["Power Ballad"] = {level = 1},
      ["Call to Action"] = {level = 1},
      ["Singing Arrow"] = {level = 1},
      ["Marching Beat"] = {level = 1},
      ["Tuning the Outcome"] = {level = 1},
      ["Song of Speed"] = {level = 1},
      ["Defensive Ditty"] = {level = 1},
      ["Unending Chant"] = {level = "X"},
      ["Nimble Knife"] = {level = "X"},
      ["Wistful Wounding"] = {level = "X"}
    }
  },
  Plagueherald = {
    box_guid = "10b86a",
    hp = info.HP.LOW,
    perks = {
      [1] = { remove = {"(-2)"}, add = {"(+0)"} },
      [2] = { remove = {"(-1)"}, add = {"(+1)"} },
      [3] = { remove = {"(-1)"}, add = {"(+1)"} },
      [4] = { remove = {"(+0)"}, add = {"(+2)"}},
      [5] = { remove = {"(+0)"}, add = {"(+2)"}},
      [6] = { add = {"(+1)", "(+1)"} },
      [7] = { add = {"(+1) (Air)"} },
      [8] = { add = {"(+1) (Air)"} },
      [9] = { add = {"(+1) (Air)"} },
      [10] = { add = {"(Poison) (Rolling)", "(Poison) (Rolling)", "(Poison) (Rolling)"} },
      [11] = { add = {"(Curse) (Rolling)", "(Curse) (Rolling)"} },
      [12] = { add = {"(Immobilize) (Rolling)", "(Immobilize) (Rolling)"} },
      [13] = { add = {"(Stun) (Rolling)"} },
      [14] = { add = {"(Stun) (Rolling)"} },
      [15] = { ignore = "S", add = {"(+1)"} }
    },
    abilities = {
      ["Biting Gnats"] = {level = 1},
      ["Spread the Plague"] = {level = 1},
      ["Wretched Swarm"] = {level = 1},
      ["Grasping Vermin"] = {level = 1},
      ["Vile Pestilence"] = {level = 1},
      ["Scattered Terror"] = {level = 1},
      ["Foul Wind"] = {level = 1},
      ["Paralyzing Bite"] = {level = 1},
      ["Gathering Doom"] = {level = 1},
      ["Creeping Curse"] = {level = 1},
      ["Winnged Congregation"] = {level = 1},
      ["Epidemic"] = {level = "X"},
      ["Blistering Vortex"] = {level = "X"},
      ["Virulent Strain"] = {level = "X"}
    }
  },
  Nightshroud = {
    box_guid = "8f7455",
    hp = info.HP.MEDIUM,
    perks = {
      [1] = { remove = {"(-1)", "(-1)"} },
      [2] = { remove = {"(-1)", "(-1)"} },
      [3] = { remove = {"(+0)", "(+0)", "(+0)", "(+0)"} },
      [4] = { add = {"(-1) (Dark)"} },
      [5] = { add = {"(-1) (Dark)"} },
      [6] = { remove = {"(-1) (Dark)"}, add = {"(+1) (Dark)"} },
      [7] = { remove = {"(-1) (Dark)"}, add = {"(+1) (Dark)"} },
      [8] = { add = {"(+1) (Invisible)"} },
      [9] = { add = {"(+1) (Invisible)"} },
      [10] = { add = {"(Muddle) (Rolling)", "(Muddle) (Rolling)", "(Muddle) (Rolling)"} },
      [11] = { add = {"(Muddle) (Rolling)", "(Muddle) (Rolling)", "(Muddle) (Rolling)"} },
      [12] = { add = {"(Heal 1 Self) (Rolling)", "(Heal 1 Self) (Rolling)"} },
      [13] = { add = {"(Curse) (Rolling)", "(Curse) (Rolling)"} },
      [14] = { add = {"(Add Target) (Rolling)"} },
      [15] = { ignore = "S", add = {"(+1)", "(+1)"} }
    },
    abilities = {
      ["Doomed Breeze"] = {level = 1},
      ["Empowering Void"] = {level = 1},
      ["Smoke Step"] = {level = 1},
      ["Cloak of Shade"] = {level = 1},
      ["Silent Force"] = {level = 1},
      ["Black Knives"] = {level = 1},
      ["Enervating Wound"] = {level = 1},
      ["Spirit of the Night"] = {level = 1},
      ["Dancing Shadows"] = {level = 1},
      ["Dark Cloud"] = {level = "X"},
      ["Concealed Dominance"] = {level = "X"},
      ["Wings of the Night"] = {level = "X"}
    }
  },
  Sawbones = {
    box_guid = "e5148c",
    info.HP.MEDIUM,
    perk = {
      [1] = { remove = {"(-1)", "(-1)"} },
      [2] = { remove = {"(-1)", "(-1)"} },
      [3] = { remove = {"(+0)", "(+0)", "(+0)", "(+0)"} },
      [4] = { remove = {"(+0)"}, add = {"(+2)"} },
      [5] = { remove = {"(+0)"}, add = {"(+2)"} },
      [6] = { add = {"(+2) (Rolling)"} },
      [7] = { add = {"(+2) (Rolling)"} },
      [8] = { add = {"(+1) (Immobilize)"} },
      [9] = { add = {"(+1) (Immobilize)"} },
      [10] = { add = {"(Wound) (Rolling)", "(Wound) (Rolling)"} },
      [11] = { add = {"(Wound) (Rolling)", "(Wound) (Rolling)"} },
      [12] = { add = {"(Stun) (Rolling)"} },
      [13] = { add = {"(Heal 3 Self) (Rolling)"} },
      [14] = { add = {"(Heal 3 Self) (Rolling)"} },
      [15] = { add = {"(Refresh)"} }
    },
    abilities = {
      ["Hand of the Surgeon"] = {level = 1},
      ["Booster Shot"] = {level = 1},
      ["Curative Mixture"] = {level = 1},
      ["Triage"] = {level = 1},
      ["Mobile Response"] = {level = 1},
      ["Syringe"] = {level = 1},
      ["Battlefield Medicine"] = {level = 1},
      ["Hold Back the Pain"] = {level = 1},
      ["Bloody Saw"] = {level = 1},
      ["First Aid"] = {level = 1},
      ["Vaccine"] = {level = "X"},
      ["Prevention Is Key"] = {level = "X"},
      ["Teamwork"] = {level = "X"}
    }
  },
  Sunkeeper = {
    box_guid = "bfe08d",
    info.HP.HIGH,
    perks = {
      [1] = { remove = {"(-1)", "(-1)"} },
      [2] = { remove = {"(-1)", "(-1)"} },
      [3] = { remove = {"(+0)", "(+0)", "(+0)", "(+0)"} },
      [4] = { remove = {"(-2)"}, add = {"(+0)"} },
      [5] = { remove = {"(+0)"}, add = {"(+2)"} },
      [6] = { add = {"(+1) (Rolling)", "(+1) (Rolling)"} },
      [7] = { add = {"(+1) (Rolling)", "(+1) (Rolling)"} },
      [8] = { add = {"(Heal 1 Self) (Rolling)", "(Heal 1 Self) (Rolling)"} },
      [9] = { add = {"(Heal 1 Self) (Rolling)", "(Heal 1 Self) (Rolling)"} },
      [10] = { add = {"(Stun) (Rolling)"} },
      [11] = { add = {"(Light) (Rolling)", "(Light) (Rolling)"} },
      [12] = { add = {"(Light) (Rolling)", "(Light) (Rolling)"} },
      [13] = { add = {"(Shield 1 Self) (Rolling)", "(Shield 1 Self) (Rolling)"} },
      [14] = { ignore = "I", add = {"(+1)", "(+1)"} },
      [15] = { ignore = "S" }
    },
    abilities = {
      ["Lay on Hands"] = {level = 1},
      ["Empowering Command"] = {level = 1},
      ["Dazzling Charge"] = {level = 1},
      ["Holy Strike"] = {level = 1},
      ["Hammer Blow"] = {level = 1},
      ["Defensive Stance"] = {level = 1},
      ["Cautious Advance"] = {level = 1},
      ["Tactical Order"] = {level = 1},
      ["Purifying Aura"] = {level = 1},
      ["Brilliant Prayer"] = {level = 1},
      ["Protective Blessing"] = {level = 1},
      ["Glorious Bolt"] = {level = "X"},
      ["Beacon of Light"] = {level = "X"},
      ["Daybreak"] = {level = "X"}
    }
  },
  Summoner = {
    box_guid = "0f9847",
    info.HP.MEDIUM,
    perks = {
      [1] = { remove = {"(-1)", "(-1)"} },
      [2] = { remove = {"(-2)"}, add = {"(+0)"} },
      [3] = { remove = {"(-1)"}, add = {"(+1)"} },
      [4] = { remove = {"(-1)"}, add = {"(+1)"} },
      [5] = { remove = {"(-1)"}, add = {"(+1)"} },
      [6] = { add = {"(+2)"} },
      [7] = { add = {"(+2)"} },
      [8] = { add = {"(Wound) (Rolling)", "(Wound) (Rolling)"} },
      [9] = { add = {"(Poison) (Rolling)", "(Poison) (Rolling)"} },
      [10] = { add = {"(Heal 1 Self) (Rolling)", "(Heal 1 Self) (Rolling)"} },
      [11] = { add = {"(Heal 1 Self) (Rolling)", "(Heal 1 Self) (Rolling)"} },
      [12] = { add = {"(Heal 1 Self) (Rolling)", "(Heal 1 Self) (Rolling)"} },
      [13] = { add = {"(Fire) (Rolling)", "(Air) (Rolling)"} },
      [14] = { add = {"(Dark) (Rolling)", "(Earth) (Rolling)"} },
      [15] = { ignore = "S", add = {"(+1)", "(+1)"} }
    },
    abilities = {
      ["Bonded Might"] = {level = 1},
      ["Unending Dominance"] = {level = 1},
      ["Unwavering Hand"] = {level = 1},
      ["Mighty Bond"] = {level = 1},
      ["Forged Ferocity"] = {level = 1},
      ["Biting Wind"] = {level = 1},
      ["Black Fire"] = {level = 1},
      ["Black Fire"] = {level = 1},
      ["Wild Animation"] = {level = 1},
      ["Ethereal Vines"] = {level = "X"},
      ["Leathery Wings"] = {level = "X"},
      ["Volatile Flame"] = {level = "X"}
    }
  },
  Doomstalker = {
    box_guid = "b7fe6d",
    info.HP.MEDIUM,
    perks = {
      [1] = { remove = {"(-1)", "(-1)"} },
      [2] = { remove = {"(-1)", "(-1)"} },
      [3] = { remove = {"(+0)", "(+0)"}, add = {"(+1)", "(+1)"} },
      [4] = { remove = {"(+0)", "(+0)"}, add = {"(+1)", "(+1)"} },
      [5] = { remove = {"(+0)", "(+0)"}, add = {"(+1)", "(+1)"} },
      [6] = { add = {"(+1) (Rolling)", "(+1) (Rolling)"} },
      [7] = { add = {"(+1) (Rolling)", "(+1) (Rolling)"} },
      [8] = { add = {"(+2) (Muddle)"} },
      [9] = { add = {"(+1) (Poison)"} },
      [10] = { add = {"(+1) (Wound)"} },
      [11] = { add = {"(+1) (Immobilize)"} },
      [12] = { add = {"(Stun)"} },
      [13] = { add = {"(Add Target) (Rolling)"} },
      [14] = { add = {"(Add Target) (Rolling)"} },
      [15] = { ignore = "S" }
    },
    abilities = {
      ["Vital Charge"] = {level = 1},
      ["Race to the Grave"] = {level = 1},
      ["Multi-Pronged Assault"] = {level = 1},
      ["Frightening Curse"] = {level = 1},
      ["Detonation"] = {level = 1},
      ["Foot Snare"] = {level = 1},
      ["Solid Bow"] = {level = 1},
      ["A Moment's Peace"] = {level = 1},
      ["Swift Trickery"] = {level = 1},
      ["Felling Swoop"] = {level = 1},
      ["Crippling Noose"] = {level = 1},
      ["Rain of Arrows"] = {level = 1},
      ["Fresh Kill"] = {level = "X"},
      ["The Hunt Begins"] = {level = "X"},
      ["Sap Life"] = {level = "X"}
    }
  },
  Diviner = {
    box_guid = "ae2ea4",
    hp = info.HP.LOW,
    perks = {
      [1] = { remove = {"(-1)", "(-1)"} },
      [2] = { remove = {"(-1)", "(-1)"} },
      [3] = { remove = {"(-2)"} },
      [4] = { remove = {"(+1)", "(+1)"}, add = {"(+3) (Shield 1 Self)"} },
      [5] = { remove = {"(+1)", "(+1)"}, add = {"(+3) (Shield 1 Self)"} },
      [6] = { remove = {"(+0)"}, add = {"(+1) (Shield 1 Ally)"} },
      [7] = { remove = {"(+0)"}, add = {"(+2) (Dark)"} },
      [8] = { remove = {"(+0)"}, add = {"(+2) (Light)"} },
      [9] = { remove = {"(+0)"}, add = {"(+3) (Muddle)"} },
      [10] = { remove = {"(+0)"}, add = {"(+2) (Curse)"} },
      [11] = { remove = {"(+0)"}, add = {"(+2) (Regenerate Self)"} },
      [12] = { remove = {"(+0)"}, add = {"(+1) (Heal 2 Ally)"} },
      [13] = { add = {"(Heal 1 Self) (Rolling)", "(Heal 1 Self) (Rolling)"} },
      [14] = { add = {"(Curse) (Rolling)", "(Curse) (Rolling)"}},
      [15] = { ignore = "S", add = {"(+1)", "(+1)"}}
    },
    abilities = {
      ["Ray of Light"] = {level = 1},
      ["Dimensional Transfer"] = {level = 1},
      ["Void Snare"] = {level = 1},
      ["Anticipate Intricacies"] = {level = 1},
      ["Cursed Ground"] = {level = 1},
      ["Peer into Battle"] = {level = 1},
      ["Protective Aura"] = {level = 1},
      ["Otherworldly Journey"] = {level = 1},
      ["Clayrvoiance"] = {level = 1},
      ["Inspiration from Beyond"] = {level = "X"},
      ["Bad Omen"] = {level = "X"},
      ["Duality Shards"] = {level = "X"}
    }
  }
}

-- indices are 1 based here
info.QUESTS = {
  ["Seeker of Xorn"] = {
    index = 16,
    number = 510
  },
  ["Merchant Class"] = {
    index = 13,
    number = 511
  },
  ["Greed is Good"] = {
    index = 10,
    number = 512
  },
  ["Finding the Cure"] = {
    index = 8,
    number = 513
  },
  ["A Study of Anatomy"] = {
    index = 1,
    number = 514
  },
  ["Law Bringer"] = {
    index = 12,
    number = 515
  },
  ["Pounds of Flesh"] = {
    index = 15,
    number = 516
  },
  ["Trophy Hunt"] = {
    index = 21,
    number = 517
  },
  ["Eternal Wanderer"] = {
    index = 6,
    number = 518
  },
  ["Battle Legend"] = {
    index = 4,
    number = 519
  },
  ["Implement of Light"] = {
    index = 11,
    number = 520
  },
  ["Take Back the Trees"] = {
    index = 17,
    number = 521
  },
  ["The Thin Places"] = {
    index = 20,
    number = 522
  },
  ["Aberrant Slayer"] = {
    index = 2,
    number = 523
  },
  ["Fearless Stand"] = {
    index = 7,
    number = 524
  },
  ["Piety in All Things"] = {
    index = 14,
    number = 525
  },
  ["Vengeance"] = {
    index = 22,
    number = 526
  },
  ["Zealot of the Blood God"] = {
    index = 23,
    number = 527
  },
  ["Goliath Toppler"] = {
    index = 9,
    number = 528
  },
  ["The Fall of Man"] = {
    index = 18,
    number = 529
  },
  ["Augmented Abilities"] = {
    index = 3,
    number = 530
  },
  ["Elemental Samples"] = {
    index = 5,
    number = 531
  },
  ["A Helping Hand"] = {
    index = 0,
    number = 532
  },
  ["The Perfect Poison"] = {
    index = 19,
    number = 533
  },
}
